### ISSUE TITLE
Deprecation Warnings when used with pg 0.21

### ISSUE THREAD

**Issue by PragTob** [skylightio/skylight-ruby#101]
[The pg gem deprecated a couple of constants in 0.21](https://github.com/ged/ruby-pg/blob/master/History.rdoc#v0210-2017-06-12-michael-granger-gedfaeriemudorg) so on every start of a process in a rails environment we know get the following warnings:

```
sidekiq : The PGconn, PGresult, and PGError constants are deprecated, and will be
sidekiq : removed as of version 1.0.
sidekiq : 
sidekiq : You should use PG::Connection, PG::Result, and PG::Error instead, respectively.
sidekiq : 
sidekiq : Called from /home/tobi/.asdf/installs/ruby/2.3.1/lib/ruby/gems/2.3.0/gems/skylight-1.4.0.beta/lib/skylight/probes.rb:81:in `require'
```

(both 1.3.1 and 1.4.0.beta as seen above)

Would be great if a fixed version could be released. Might PR it myself tomorrow (should be easy enough I hope... depending on which pg version has what constants available). If so, should I PR it against 1.3.1 or master? :)

**Comment by wagenet** [comment]
We hook into `require` to recognize when some libraries are loaded in order to instrument them, which is why you see it in the backtrace. We don't use the pg gem or any of these constants.

**Comment by PragTob** [comment]
huh that was fast o_O Thanks.

Guess I should have taken a look at the code, sorry :| Well then fun hunting ahead to see who actually does this.

**Comment by wagenet** [comment]
No worries. Good luck!
