### ISSUE TITLE
Activate based on environment variable?

### ISSUE THREAD

**Issue by arr-dev** [skylightio/skylight-ruby#102]
Would it be easier to activate Skylight based on some ENV, like `SKYLIGHT_ENABLED`, 
or exposing `activate` method in configuration?

Currently, it's easy to forget to  append environment to the list of enabled envs.

**Comment by wagenet** [comment]
@arr-dev do you mind telling me the name of the environment you're using and why you're using it instead of production? I don't doubt that you have a good reason, just trying to make sure I understand your specific usage.

**Comment by arr-dev** [comment]
Well, currently it's a staging environment, but there could be others in the future.
I know we could run the app under production env with staging config, like on heroku, 
but we use staging so we are able to identify and separate instances,
in error reporting, monitoring, tracking, etc.
I see that this is already supported in skylight, and believe that this way it would be easier to set up.

**Comment by wagenet** [comment]
I think this is something we can probably do. Basically it would override the settings in application.rb if present and would enable unless set to "false", "no" or 0, or something along those lines. Would that work for you?

**Comment by arr-dev** [comment]
Yeah. I could work up a PR if you are interested?

**Comment by wagenet** [comment]
Yeah, that would be great! I'm thinking the place to do this would be in the railtie, since that's the only place we pay attention to the environments list. Make sure you take a look at our [CONTRIBUTING.md](https://github.com/skylightio/skylight-ruby/blob/master/CONTRIBUTING.md) before sending anything.
