### ISSUE TITLE
How to mock an Instrumenter?

### ISSUE THREAD

**Issue by agdiaz** [skylightio/skylight-ruby#103]
I'm trying to use a custom Middleware in an API based in **Grape**. I've configured Skylight and it's working well in production environment. 

The middleware is based in one defined in this ruby gem (it seems to be discontinued): [grape-skylight](https://github.com/nickcharlton/grape-skylight)

```ruby
require 'grape'
require 'skylight'

module Skylight
  module Grape
    # Middleware to enable Skylight reporting with Grape.
    class Middleware < ::Grape::Middleware::Base
      def initialize(app)
        @app = app
      end

      def call(env)
        @app.call(env).tap do
          # get the instrumenter instance, or skip
          instrumenter = Skylight::Instrumenter.instance
          next unless instrumenter
          trace = instrumenter.current_trace
          next unless trace

          # produces a string to represent the route like: GET /hello/:name
          request = env['api.endpoint'].routes.first
          request_route = request.route_path.sub(/\(\.:format\)\z/, '')
          name = "#{request.route_method} #{request_route}"

          # set the endpoint to our route
          trace.endpoint = name
        end
      end
    end
  end
end
```

My problem is that when I want to test it using RSpec:

```ruby
require "api_helper"
require "middlewares/grape_skylight/endpoint_reporter"

describe GrapeSkylight::EndpointReporter do
  context "when an endpoint uses the Skylight Grape Middleware" do
    let(:app) { Grape::API.dup.tap { |api| api.use described_class } }

    before do
      app.get "/hello/:name" do
        name_param = params["name"]
        "Hello #{name_param}"
      end
    end

    it "wraps a request in a Skylight instrument" do
      expect(::Skylight).to receive(:trace).with("GET /hello/:name").and_yield

      get "/hello/world"

      expect(last_response.status).to eq(200)
      expect(last_response.body).to eq("Hello world")
    end
  end
end
```

It always fails like this:

> Failure/Error: expect(::Skylight).to receive(:trace).with('GET /hello/:name').and_yield
>
>       (Skylight).trace("GET /hello/:name")
>           expected: 1 time with arguments: ("GET /hello/:name")
>           received: 0 times

Inspecting the source code, I found there is no one instrumenter instance:

```ruby
def call(env)
        @app.call(env).tap do
          # get the instrumenter instance, or skip
          instrumenter = Skylight::Instrumenter.instance # <-- is nil
          next unless instrumenter 
```

My question is if exists any way to mock the Instrumenter?

Thanks in advance,

**Comment by wagenet** [comment]
Skylight has built-in Grape support. Is that not working for you? What version of Grape are you using?

**Comment by agdiaz** [comment]
Hi @wagenet, I'm using the next version:

```
 grape (0.5.0)
	Summary: A simple Ruby framework for building REST-like APIs.
	Homepage: https://github.com/intridea/grape
	Path: ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.5.0
```

I started using the tool with any custom middleware and works fine but in the Dashboard, I only saw `Rack` endpoint. Using the middleware I can see the endpoints:

### Before
![image](https://user-images.githubusercontent.com/1646576/30988112-a8917828-a46f-11e7-8f6f-faf849288767.png)

## After
<img width="980" alt="screen shot 2017-09-28 at 17 08 54" src="https://user-images.githubusercontent.com/1646576/30988210-fb3af81a-a46f-11e7-9d3c-de52cb606897.png">

**Comment by wagenet** [comment]
Grape 0.5.0 is over 4 years old. We only support grape 0.10+ though 0.13+ is recommended.

**Comment by agdiaz** [comment]
Thanks @wagenet, I will update the grape version.

**Comment by wagenet** [comment]
Let me know how it goes. It should work without any other gems. Make sure to follow the instructions here: https://www.skylight.io/support/advanced-setup#grape-1
