### ISSUE TITLE
All requests are grouped into the OmniAuth::Builder endpoint

### ISSUE THREAD

**Issue by jeffblake** [skylightio/skylight-ruby#106]
Recently re-activated my Skylight account, and I'm getting a strange problem where all my requests are going into the `OmniAuth::Builder` endpoint. I've tried recreating a new app from scratch, no dice.

Rails 5.1.4
Heroku
Skylight 1.4.3

I don't think it has anything to do with omniauth, I think its just because omniauth is last in the middleware chain.
But, anyway, In an initializer I have

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :quickbooks, setup: true
  provider :open_id, name: 'intuit', identifier: 'https://openid.intuit.com/openid/xrds'
  provider :stripe_connect, setup: true
  provider :mailchimp, setup: true
  provider :eventbrite, setup: true
  provider :braintree_auth, setup: true

  facebook_api_version = AppProvider::FacebookProvider.api_version
  provider :facebook, setup: true,
    client_options: {
    site: "https://graph.facebook.com/#{facebook_api_version}",
    authorize_url: "https://www.facebook.com/#{facebook_api_version}/dialog/oauth"
    },
    token_params: { parse: :json }

  on_failure do |env|
    Users::OmniauthCallbacksController.action(:failure).call(env)
  end
end
```

`heroku run rails middleware`
```
[SKYLIGHT] [1.4.3] Skylight agent enabled
use Rack::MiniProfiler
use Skylight::Middleware
use Rack::Sendfile
use Rack::Cors
use ActionDispatch::Static
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Timeout
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use ActionDispatch::RemoteIp
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use Bugsnag::Rack
use ActionDispatch::Callbacks
use ActionDispatch::Cookies
use ActionDispatch::Session::CacheStore
use ActionDispatch::Flash
use CatchJsonParseErrors
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
use Remotipart::Middleware
use Rack::Attack
use Rack::Deflater
use OmniAuth::Builder
```

**Comment by jeffblake** [comment]
Removing omniauth just causes requests to now go under `Rack`

<img width="1322" alt="screen shot 2017-11-01 at 6 28 25 pm" src="https://user-images.githubusercontent.com/620564/32305394-89b17402-bf32-11e7-861a-951c2065cae1.png">

**Comment by wagenet** [comment]
@jeffblake thanks for reporting and sorry for the trouble! Can you contact us via our in-app messenger. This will make it easier for me to discuss private details of your account.

**Comment by wagenet** [comment]
In the meantime, you can temporarily disable the middleware probe with `config.skylight.probes -= ['middleware']`.

**Comment by wagenet** [comment]
Looking at the output of your `heroku run rails middleware` I'm surprised to see that there's no "run" item at the end. In our main Rails app, the output of the same command is:

```
use Skylight::Middleware
use Rack::Attack
use HireFire::Middleware
use Rack::Sendfile
use ActionDispatch::Static
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use ActionDispatch::RemoteIp
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use Bugsnag::Rack
use ActionDispatch::Callbacks
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Rack::SSL
use OmniAuth::Builder
run Direwolf::Application.routes
```

**Comment by jeffblake** [comment]
Here is `CatchJsonParseErrors.rb`

```
class CatchJsonParseErrors
  def initialize(app)
    @app = app
  end

  def call(env)
    begin
      @app.call(env)
    rescue ActionDispatch::Http::Parameters::ParseError => error
      if env['CONTENT_TYPE'] =~ /application\/json/ && env['REQUEST_PATH'].match?(/api\/public/)
        error_output = "There was a problem in the JSON you submitted: #{error}"
        return [
          400, { "Content-Type" => "application/json" },
          [ { status: 400, error: error_output }.to_json ]
        ]
      else
        raise error
      end
    end
  end
end
```

I also tried removing that middleware and the MiniProfiler middleware, to no success.

Removing the skylight middleware probe fixes it, but I'd like to use the probe.

Sorry, I do have a `run` command, I just omitted it

**Comment by wagenet** [comment]
If you take a look at the source here, you can see how it works: https://github.com/skylightio/skylight-ruby/blob/master/lib/skylight/probes/middleware.rb. The line that's relevant for you is line 30. The idea here is that for each middleware we enter, we set the endpoint name to match the middleware. However, we're expecting that the very last thing we do in a normal Rails request is going to be entering the main application where we then set the endpoint name to the name of the controller action. Does this make sense?
​
​If you're willing to do a little local hacking, you can try turning on the agent in development and then adding logging around line 30 of probes/middleware.rb and also line 21 of https://github.com/skylightio/skylight-ruby/blob/master/lib/skylight/normalizers/action_controller/process_action.rb. The ProcessAction name should be setting after all the middleware, but it seems that it's either not getting hit or a middleware one is getting hit afterwards.

**Comment by jeffblake** [comment]
All good now. It seems time was the answer.

**Comment by wagenet** [comment]
@jeffblake it just resolve itself? That's nice, though it always makes me a bit uncomfortable when I don't know the root cause!
