### ISSUE TITLE
Support for Sidekiq

### ISSUE THREAD

**Issue by icapuccio** [skylightio/skylight-ruby#108]
Is there support for Sidekiq workers? My app relies heavily on them 🙏

**Comment by wagenet** [comment]
@icapuccio There isn't currently. The desired behavior for tracking Sidekiq is fairly different than it is for tracking web requests. That said, we're still continuing to explore the possibility of supporting this in the future. I recommend contacting us via one of our support channels so we can make a note about your interest on your account.
