### ISSUE TITLE
Invalid Span Nesting Error, No Stats

### ISSUE THREAD

**Issue by dfockler** [skylightio/skylight-ruby#118]
We're getting this repeatedly on our production server in `skylight.log`.
```
ERROR -- : [SKYLIGHT] [1.5.0] invalid span nesting
```
When I run `bundle exec skylight doctor` I also get an issue about SSL not being able to connect. Not sure if these two things are related or not.

**Comment by gitKrystan** [comment]
Hi there. @wagenet manages this repo, but he's out today. Can you ping us at support@skylight.io or via the in-app messenger? I have some suggestions to help debug.

**Comment by wagenet** [comment]
This error means that spans (the individual items we instrument) are being closed incorrectly. The most common cause of this is a Middleware that doesn't correctly conform to the SPEC.

When logs don't show sufficient detail one option is to try running with `SKYLIGHT_ENABLE_TRACE_LOGS=true` in your environment. This will make the logs very noisy, but will output a lot more potentially useful debugging information.

We're also working to improve overall error logging for future agent releases.

**Comment by dfockler** [comment]
So I don't think `invalid span nesting` is the issue causing no stats.

**Comment by wagenet** [comment]
@dfockler it could cause it if _every_ request was invalidly nested. Can you give 1.6.0 or the latest 2.0 beta a try? Those have some improved logging (especially the beta).

**Comment by dfockler** [comment]
@wagenet I tried on my local machine with the same configuration and it worked, so it's definitely a network issue on our server.

**Comment by wagenet** [comment]
Got it.
