### ISSUE TITLE
Getting SystemStackError (stack level too deep) when used with middleware

### ISSUE THREAD

**Issue by dachinat** [skylightio/skylight-ruby#122]
If I'll `config.skylight.probes -= ['middleware']` then it does not cause an error.

My middleware looks like

```
class SessionFilter
  def initialize(app)
    @app = app
  end

  def call(env)
    if env["PATH_INFO"].start_with?("/users/auth")
      session_filter_loosen.build(@app).call(env)
    else
      session_filter_suppress.build(@app).call(env)
    end
  end

  private
  def session_filter_suppress
    @session_filter_suppress ||= begin
      ActionDispatch::MiddlewareStack.new.tap do |middleware|
        Rails.application.config.session_store :disabled
        middleware.delete ActionDispatch::Cookies
        middleware.delete ActionDispatch::Session::CookieStore
      end
    end
  end

  def session_filter_loosen
    @session_filter_loosen ||= begin
      ActionDispatch::MiddlewareStack.new.tap do |middleware|
        middleware.use ActionDispatch::Cookies
        middleware.use ActionDispatch::Session::CookieStore, Rails.application.config.session_options
      end
    end
  end
end
```

It's for enabling cookies/sessions only for specific endpoints.

When I use Skylight in combination with my middleware, I'm getting

```
SystemStackError (stack level too deep):
app/middleware/session_filter.rb:10:in `call'
```

Is there some conflict? Do you think it's easily solvable with some configuration on the Skylight side?

**Comment by zvkemp** [comment]
Hi @dachinat,
It looks like building an `ActionDispatch::MiddlewareStack` multiple times causes Skylight's middleware probe to recurse. We can look into it, but this is an unusual usage of `ActionDispatch::MiddlewareStack` (there are likely several other issues you'd need to contend with here, including the fact that the `:disabled` session store config could bleed into the `session_filter_loosen` stack). 

Could you possibly use [`Rack::Builder`](https://www.rubydoc.info/gems/rack/Rack/Builder) here instead?

**Comment by dachinat** [comment]
Hi @zvkemp 
Thanks for taking a look at this.

Sure, I'll try Rack::Builder
