### ISSUE TITLE
skylight.yml question

### ISSUE THREAD

**Issue by kapso** [skylightio/skylight-ruby#129]
Curious, why do you have `---` on line #1. I tried removing that, and Skylight started throwing error - `Failed to extract binds from SQL query` and the app become really slow.

<img width="259" alt="screen shot 2018-09-05 at 8 27 17 pm" src="https://user-images.githubusercontent.com/344198/45133466-2f0ede80-b14a-11e8-8ba5-b0684d26a0b1.png">

**Comment by zvkemp** [comment]
Hi @kapso, thanks for the report! The triple-dash indicates the start of a YAML document, and is safe to remove in this case.

The SQL binds issue is unrelated. If you're willing to share the string of SQL that couldn't be parsed, we can use it to improve our sequel lexer for the next version — please drop us a note at https://www.skylight.io/contact if you'd like to keep it out of the public forum (and please feel free to mask any sensitive data found in the query).

**Comment by kapso** [comment]
This is what I was seeing in the logs

<img width="1195" alt="screen shot 2018-09-05 at 8 13 34 pm" src="https://user-images.githubusercontent.com/344198/45172694-f6f3b400-b1ba-11e8-887d-c305aec8d675.png">

**Comment by zvkemp** [comment]
Thanks @kapso. This appears to be an issue with schema-qualified table names (i.e., "schema"."table"[."column"]). We have a fix under review, so this should land in our next beta release of the `skylight` gem.

**Comment by kapso** [comment]
Is there a way to easily enable/disable the plugin? Or the only way is to remove the gem from `Gemfile`?

I would like to disable Skylight, until the above issue is fixed.

**Comment by wagenet** [comment]
Try setting `log_sql_parse_errors` to `false` in your `skylight.yml`.

**Comment by zvkemp** [comment]
Hi @kapso, the latest beta version should fix your sql-parsing issue. Add `gem 'skylight', '3.1.0.beta'` to your Gemfile to install.

**Comment by kapso** [comment]
Got it. So I can remove `log_sql_parse_errors: false` ?

**Comment by zvkemp** [comment]
Yes, it should be safe to do so.
