### ISSUE TITLE
Skylight BodyProxy Breaks Rack::ContentLength Middleware

### ISSUE THREAD

**Issue by jeffnappi** [skylightio/skylight-ruby#131]
When using Skylight, the Rack::ContentLength middleware ceases to function.

I've traced the issue to the use of `to_ary` in Rack::ContentLength:

https://github.com/rack/rack/blob/8376dd11e6526a53432ee59b7a5d092bda9fc901/lib/rack/content_length.rb#L21

**Comment by wagenet** [comment]
@jeffnappi thanks for reporting this. Can you provide a reproduction case? We make a point of handling `to_ary` correctly in the BodyProxy. https://github.com/skylightio/skylight-ruby/blob/master/skylight-core/lib/skylight/core/middleware.rb#L13

**Comment by jeffnappi** [comment]
@wagenet I've dug into this further and although Skylight does break the use of `Rack::ContentLength`, I believe the issue is in `Rack` - not Skylight.

It appears as if `Rack::ContentLength` is incompatible with BodyProxy responses, but I have to admit I am not familiar enough with Rack to know why.

Perhaps because they wrap the body in a BodyProxy themselves and they cannot be nested? https://github.com/rack/rack/blob/20d7be16bd0c73602c3b54c1211b998bb3c73c3a/lib/rack/content_length.rb#L29

**Comment by wagenet** [comment]
@jeffnappi it's possible. Any chance you could put together a test case? Even if the problem is in rack, we may need to fix it on our end. Might also be able to submit a fix to Rack.

**Comment by wagenet** [comment]
@jeffnappi `spec/integration/rails_spec.rb` might not be a bad place. Let me know if you need any guidance. Alternatively, you can explain what exactly it is that you're expecting and isn't working.

**Comment by yeuem1vannam** [comment]
I'm not sure this issue is related to our situation or not, but I'd like to share some information about a bug in our staging environment.
Our Ruby on Rails app running on AWS ECS, after integrate with skylight, the container keeps crashing after 4-6hrs. There is no heavy load, the crash just started from a healthcheck request from ALB ( once per 20 seconds )
## Overview on CloudWatch
CPU CPUUtilization
![image](https://user-images.githubusercontent.com/2409560/51963936-6343bc80-24a8-11e9-8ebb-e341de821114.png)

MemoryUtilization
![image](https://user-images.githubusercontent.com/2409560/51963951-6c348e00-24a8-11e9-9077-e1554ef6aa66.png)

## Error happen (sample) 01:00:13
```text
I, [2019-02-21T01:00:13.942475 #29] INFO -- : [b30e3ab5-2e09-47de-87ab-a6b11c93dc4b] Started GET "/healthcheck" for 127.0.0.1 at 2019-02-21 01:00:13 +0000
Error reached top of thread-pool: stack level too deep (SystemStackError)
2019/02/21 01:00:14 httputil: ReverseProxy read error during body copy: unexpected EOF
```
![image](https://user-images.githubusercontent.com/2409560/53212559-be706580-3688-11e9-8b85-fa61a57497ec.png)
## Container crashing because of CPU dump 01:25:47
```
I, [2019-02-21T01:25:47.721792 #29] INFO -- : [470a7b1c-d146-4c29-a488-5ccb4379f989] Started GET "/healthcheck" for 127.0.0.1 at 2019-02-21 01:25:47 +0000
load_missing_constant(ActionController, UnknownAction)
load_missing_constant(Object, UnknownAction)
load_missing_constant(CGI, Session)
load_missing_constant(Object, Session)
load_missing_constant(Object, Mongoid)
load_missing_constant(Object, Sinatra)
/usr/local/bundle/gems/skylight-core-3.1.4/lib/skylight/core/probes/middleware.rb:26:in `call'
/usr/local/bundle/gems/skylight-core-3.1.4/lib/skylight/core/probes/middleware.rb:26:in `call'
/usr/local/bundle/gems/skylight-core-3.1.4/lib/skylight/core/probes/middleware.rb:26:in `call'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/engine.rb:522:in `call'
/usr/local/bundle/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
/usr/local/bundle/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
/usr/local/bundle/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
/usr/local/bundle/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
/usr/local/bundle/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
2019/02/21 01:25:50 http: proxy error: context canceled
2019/02/21 01:25:50 http: proxy error: context canceled
2019-02-21 01:25:52 +0000: Rack app error handling request { GET /healthcheck }
#<SystemStackError: stack level too deep>
```
![image](https://user-images.githubusercontent.com/2409560/53212589-d811ad00-3688-11e9-9eee-94a5f3d63ce1.png)

## Within 01:00:13 to 01:25:47
- Request to /healthcheck keep crashing
- Request to other place works normally
```
I, [2019-02-21T01:09:14.463344 #29] INFO -- : [19fbf66c-893a-4e75-a052-dc1743945a93] Started GET "/healthcheck" for 127.0.0.1 at 2019-02-21 01:09:14 +0000
Error reached top of thread-pool: stack level too deep (SystemStackError)
2019/02/21 01:09:14 httputil: ReverseProxy read error during body copy: unexpected EOF
I, [2019-02-21T01:09:19.454284 #29] INFO -- : [55e1188e-1e8e-412e-a344-779e8bb84899] Started GET "/" for XX.XXX.XXX.XXX at 2019-02-21 01:09:19 +0000
I, [2019-02-21T01:09:19.618559 #29] INFO -- : [55e1188e-1e8e-412e-a344-779e8bb84899] Completed 200 OK in 159ms (Views: 49.5ms | ActiveRecord: 9.8ms)
```

## Rack stack

```ruby
use Rack::Sendfile
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use ActionDispatch::RemoteIp
use Sprockets::Rails::QuietAssets
use Rails::Rack::Logger
use Sonyged::Middleware::HealthcheckMiddleware # handling /healthcheck, return immediately
use Skylight::Middleware                       # skylight
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::Callbacks
use ActionDispatch::Cookies
use ActionDispatch::Session::CacheStore
use ActionDispatch::Flash
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
# ...
```

The weird thing that we have a `HealthcheckMiddleware` stand in front of `Skylight::Middleware`, which will return status 200 immediately when receiving request to `/healthcheck`, but it seems that skylight still collect some information.

**Comment by wagenet** [comment]
@yeuem1vannam thanks for reaching out and sorry that you're having trouble. I haven't seen anything like this before with out agent. Unless something very strange going on, there's no way that Skylight should be instrumenting requests if the HealthcheckMiddleware is returning and is truly in front of Skylight. How are you checking the middleware order?

**Comment by yeuem1vannam** [comment]
@wagenet 
In `config/application.rb` we added
```ruby
config.skylight.middleware_position = { after: Sonyged::Middleware::HealthcheckMiddleware }
```
then in the starting script of the server, I added
```bash
export RAILS_ENV=staging
bundle exec rails middleware # it print the stack to STDOUT log
bundle exec puma -C config/puma.rb
```

The HealthcheckMiddleware is quite simple
```ruby
    class HealthcheckMiddleware < BaseMiddleware
      OK_RESPONSE = [200, { "Content-Type" => "text/plain" }, ["It's alive!".freeze]]

      def initialize(app)
        @app = app
      end

      def call(env)
        if env["PATH_INFO"] == "/healthcheck"
          return OK_RESPONSE
        end
        @app.call env
      end
    end
```

**Comment by wagenet** [comment]
@yeuem1vannam The only thing that strikes me as possibly strange here is that you're saying that somehow our middleware is still getting hit even for health checks. AFAICT, this shouldn't be possible! Anyway, I'm not seeing any indications that we're at fault here, but if you want to pursue this further, we'd be happy to keep at it over to our standard support chat, which you can access via the question-mark in the bottom right of the logged in app, or support@skylight.io.
