### ISSUE TITLE
Skylight integration for Slack

### ISSUE THREAD

**Issue by ProgrammingSam** [skylightio/skylight-ruby#137]
I would like some sort of Slack integration (Webhook) of Skylight to be able to monitor errors (like 404/500). 

Do you plan on doing this kind of development in the futur ? 

Thanks for your work ! 

Regards, 

Sami

**Comment by wagenet** [comment]
@ProgrammingSam Looks like you've also reached out via our support channels. I'm going to go ahead and close this issue for now and we'll address it via support. It's getting close to the end of the day here so we may not get back to you until Monday. Thanks for your interest!
