### ISSUE TITLE
Changelog for 4.0.0

### ISSUE THREAD

**Issue by rdunlop** [skylightio/skylight-ruby#138]
I see that 4.0.0 was released yesterday (https://rubygems.org/gems/skylight).

There are no release notes in the CHANGELOG.md, nor on the Releases page.

This doesn't make it simple to evaluate whether there are any changes that I should be concerned about before upgrading this gem.

Please add release notes.

Looking back, I'm unsure how to see the code changes for previous versions either...e.g. https://github.com/skylightio/skylight-ruby/compare/4.0.0.beta3...4.0.0.beta2 shows no differences? how is this possible?

**Comment by zvkemp** [comment]
Thanks for bringing this to our attention - the public master branch has now been synced with our development repo. The changelog is [here](https://github.com/skylightio/skylight-ruby/blob/master/CHANGELOG.md#400-may-6-2019).
