### ISSUE TITLE
Ignore specific route / Kubernetes alive gets thousands of hits

### ISSUE THREAD

**Issue by leifcr** [skylightio/skylight-ruby#140]
Feature request: Ignore specific routes from being probed.

When deploying to a kubernetes cluster with X number of containers, the alive polling for a container results in thousands of skylight probes/hits. Would it be possible to filter specific urls, middleware or similar to avoid logging alive entries?

I do think this might apply to other deployment scenarios where using an url to check for readyness or liveliness.

**Comment by zvkemp** [comment]
Hi @leifcr! You can add your healthcheck/liveness endpoints to the [ignored endpoints](https://www.skylight.io/support/advanced-setup#ignoring-heartbeat-endpoints) config.

**Comment by leifcr** [comment]
@zvkemp Thanks. works!
