### ISSUE TITLE
Lots of object allocations in `Skylight::Helpers`

### ISSUE THREAD

**Issue by hmcfletch** [skylightio/skylight-ruby#144]
I have been doing a bunch of profiling of our Rails app using the `derailed_benchmarks` gem. While investigating object allocations I found this:

```
allocated memory by location
-----------------------------------
   3969040  .../activesupport-5.2.3/lib/active_support/core_ext/object/json.rb:171
    869280  .../activerecord-5.2.3/lib/active_record/result.rb:134
    837520  .../skylight-4.1.2/lib/skylight/helpers.rb:142
    837520  .../skylight-4.1.2/lib/skylight/helpers.rb:147
    758590  .../activesupport-5.2.3/lib/active_support/json/encoding.rb:22
```

We do make use of method instrumentation and instrumented blocks a fair bit. I am assuming this heavy allocation is a result of that and am seeking confirmation. 

[`Skylight::Helpers` Line 142](https://github.com/skylightio/skylight-ruby/blob/v4.1.2/lib/skylight/helpers.rb#L142)
[`Skylight::Helpers` Line 147](https://github.com/skylightio/skylight-ruby/blob/v4.1.2/lib/skylight/helpers.rb#L147)

Versions:
- Skylight: 4.1.2
- Ruby: 2.6.2
- Rails: 5.2.3

Skylight has been a huge benefit to us. Thanks for the great work!

**Comment by wagenet** [comment]
Yes, this would definitely be related to use of method and block instrumentation. I think it's possible that we could improve this by freezing a couple of strings. I'll talk with the team about it. Thanks for bringing it to our attention!

**Comment by wagenet** [comment]
@hmcfletch are you able to give this branch a try? https://github.com/skylightio/skylight-ruby/tree/reduce-allocations

**Comment by hmcfletch** [comment]
Unfortunately, I didn't see a reduction in allocations

**Comment by wagenet** [comment]
I wonder if it's possible that it is misattributing allocations to our code since we're writing a new method to wrap your original one.

**Comment by wagenet** [comment]
I do think we can avoid always initializing the empty meta hash. I've pushed another commit to the branch. Thanks for working with us on this!

**Comment by hmcfletch** [comment]
The two lines that it references are the `span = Skylight.instrument...` and `meta = {}` lines. Which are specifically Skylight code, so I think that it is correct.

**Comment by hmcfletch** [comment]
Happy to help!

**Comment by wagenet** [comment]
It's just curious to me that you wouldn't see any benefit from freezing the values in the `Skylight.instrument` call. In theory freezing the Strings should cause them to be re-used on subsequent calls.

**Comment by hmcfletch** [comment]
It's possible I didn't do something correctly on that run. I forked the gem and am playing with it. I'll create a PR if I find anything useful.

**Comment by hmcfletch** [comment]
OK, from what I can tell, it isn't the strings, it is the span itself. I refactored `meta` away with the following:

```ruby
begin
  ret = send(:before_instrument_#{name}, *args, &blk)
  Skylight.done(span) if span
  ret
rescue Exception => e
  Skylight.done(span, { exception_object: e }) if span
  raise e
end
```

In the end, I had instrumented a pretty hot method, so I it made sense that I was seeing a ton of allocations. The real fix for this, is for me to be a little less cavalier with `instrument_method` in my code.

**Comment by wagenet** [comment]
@hmcfletch thanks for looking into this. Would you mind telling me a bit more about what you were instrumenting?

**Comment by hmcfletch** [comment]
The method I had instrumented was a part of our authorization policy. At one point I was concerned that this was a bottleneck during our json response rendering phase, as the policy was checked for about half of the attributes returned. Instrumenting that method created a span for each of those policy checks, which was a bad thing. :p 

I think in the end I misunderstood the cost of some of the custom instrumentation. Instrumenting such a hot method was not a good idea. You do mention in the docs a little about not over instrumenting, but there might be a place for a special call out for adding custom instrumentation that gets called *a lot* each request. Might even be something to highlight on the UI, saying that a custom span title was track way more than it should be (more than 20?).

**Comment by p8** [comment]
@wagenet Maybe we should use string interning? https://github.com/mime-types/ruby-mime-types/commit/1c8e13c7cd6b187c564afe8a05cadf51d8880fe1
The helpers file also misses the `frozen_string_literal` pragma.

**Comment by p8** [comment]
Hmm not what I expected.
Using `derailed_benchmarks` I'm seeing:
   allocated objects by gem:
   40486  skylight-core-4.1.2
With string interning and frozen_string_literal` pragma.
   allocated objects by gem:
   40523  skylight-core-4.1.2

**Comment by p8** [comment]
Ah, ok it's mostly in skylight-core:
```allocated memory by location
   4662421  ~/.gem/ruby/2.6.5/gems/skylight-core-4.1.2/lib/skylight/core/probes.rb:120
```
Adding the string interning and frozen_string_literal doesn't help.

**Comment by p8** [comment]
Zeitwerk had the same problem https://github.com/fxn/zeitwerk/pull/34

**Comment by wagenet** [comment]
@p8 I'm looking at `probes.rb` and I don't see anything that seems like it could cause anywhere near this number of allocations. Are you certain that we're getting correctly attributed? My concern would be that anything allocated during a require is getting incorrectly attributed to us.

**Comment by wagenet** [comment]
Ah, we've seen this before https://www.skylight.io/support/troubleshooting#i-ran-a-memory-profiler-why-are-so-many-object-allocations-attributed-to-skylight

**Comment by p8** [comment]
@wagenet Ah that explains a lot. :) thanks.
