### ISSUE TITLE
GraphQL probe stopped working

### ISSUE THREAD

**Issue by coding-chimp** [skylightio/skylight-ruby#145]
Hey, we recently updated to the newest version of graphql-ruby and since then the graphql probe seems to be broken. I'm pretty sure it's because they [changed the naming of their ActiveSupport::Notification events](https://github.com/rmosolgo/graphql-ruby/pull/2562). I guess you'd just need to update the `register` calls in `Skylight::Core::Normalizers::GraphQL`,  but the change would not be compatible with older versions of graphql-ruby.

Let me know if I can lend a hand. 🙂

**Comment by coding-chimp** [comment]
I have a [fork with a fix](https://github.com/skylightio/skylight-ruby/compare/master...askcharlie:fix-graphql-probe?expand=1) that we're currently using. I'd be happy to open a PR, I'm just not sure how you'll want to handle backwards compatibility.

**Comment by zvkemp** [comment]
Hi @coding-chimp, thanks for the heads-up, and thank you for providing your fork. You are right that we will need to do this in a way that provides backwards compatibility, so at this point a PR is not necessary. We will update you here when this has been fixed in an official release.

**Comment by zvkemp** [comment]
@coding-chimp this issue is resolved in [version 4.2.2](https://rubygems.org/gems/skylight/versions/4.2.2)

**Comment by coding-chimp** [comment]
@zvkemp Thank you very much! We will give that a spin. 🙂
