### ISSUE TITLE
No changelog for 4.2.2 or recent commits in repository

### ISSUE THREAD

**Issue by Antsiscool** [skylightio/skylight-ruby#146]
Hi - There is no change for for 4.2.2 (Or 4.2.1). 

And the most recent commit was from October last year.

**Comment by zvkemp** [comment]
The current master branch targets our next major release; you'll find the updated [changelog](https://github.com/skylightio/skylight-ruby/blob/maint/4.2.x/CHANGELOG.md) and commits for 4.2.2 in the maint/4.2.x branch.
