### ISSUE TITLE
Stopped reporting after updating from 4.2.3 to 4.3.0

### ISSUE THREAD

**Issue by emad-elsaid** [skylightio/skylight-ruby#147]
I noticed that the reporting went offline after deploying the gem update from 4.2.3 to 4.3.0.

The update bump was introduced in dependabot PR https://github.com/emad-elsaid/rubyfunctions/pull/50 and was deployed yesterday evening.

The project is opensource so you can check all changes and the project status, and it's part of skylight.io opensource 
https://oss.skylight.io/app/applications/wwchw2UGlt0N/1587128460/4h13m/endpoints

Let me know if you need me to do any investigation on my side.

**Comment by DanielWright** [comment]
Hi @emad-elsaid,

Thanks for reaching out. Are there any useful error messages in your deployed app's `log/skylight.log` file?

**Comment by emad-elsaid** [comment]
I see in the log/skylight.log this line :
```
W, [2020-04-19T22:14:07.098796 #7]  WARN -- Skylight: Unable to start Instrumenter due to a configuration error: authentication token required
```
when I get the env I find there is an env variable set `SKYLIGHT_AUTHENTICATION=xxxxxxxxxx`

that is what I see right now in the logs, I double checked now if it's still offline but I see the application started to report normally, although the logs shows it needs auth token.

**Comment by DanielWright** [comment]
Hi @emad-elsaid,

To confirm I've understood correctly:

1. Your log indicated an issue with authentication (either a missing or invalid token).
2. You double-checked your deployment environment includes the `SKYLIGHT_AUTHENTICATION` token, and it did.
3. The app has begun reporting successfully.

Is that correct?  I have to admit I can't think of a simple reason why a gem upgrade would cause a temporary authentication-token issue, but I'm thrilled to hear it's working again!

Please let me know if your issues come up again. Thanks for using Skylight!

**Comment by emad-elsaid** [comment]
Yup, that's correct, your points describe what happened correctly
