### ISSUE TITLE
Sqreen and Skylight conflict resolved by beta

### ISSUE THREAD

**Issue by lloeki** [skylightio/skylight-ruby#155]
A Sqreen customer reported that he received no data from Sqreen following an upgrade. As it turns out, this upgrade enables Module#prepend by default, the result being that when Skylight instruments the same code as we do (more precisely some of our middlewares) we are evicted from the call chain.

At some point I was confused because I saw on Skylight source code that [you were using Module#prepend](https://github.com/skylightio/skylight-ruby/blob/4b7dac150d0c6a7d05a87c0ffc38b2e0ed1ad2c7/lib/skylight/probes/middleware.rb#L116), but on the 4.3.1 gem you're not, and I failed to notice that code is on a [separate maint/4.3.x branch](https://github.com/skylightio/skylight-ruby/blob/47f370c55258c4972d7bccded2d3cc220c395179/skylight-core/lib/skylight/core/probes/middleware.rb#L21-L23). So you did the job but it's not released yet. Or so I thought!

I crawled your closed issues and found [this one](https://github.com/skylightio/skylight-ruby/issues/149#issuecomment-654958423) which describes [typical](https://github.com/newrelic/newrelic-ruby-agent/issues/461) [conflicts](https://github.com/scoutapp/scout_apm_ruby/issues/278) between alias method chain and prepend, where you mention having a [5.0.0.beta release](https://rubygems.org/gems/skylight/versions/5.0.0.beta). As mentioned in the comment, it introduces a higher dependency on ActiveSupport than before, but since they're using Rails 5.2 it seems they're good to go.

I tried it agains our latest version of Sqreen and it operates correctly without any hacks.

So, this is not really an issue as much as it is twofold feedback:

- good job on the prepend work, it works great
- you might want to consider moving forward with a non-beta release (if that falls in line with your other internal requirements for that 5.0 line)

And an additional note: congrats on your agent code, it was a pleasure to follow and read.

**Comment by zvkemp** [comment]
Hi @lloeki , thanks for the kind words! The 5.0 line is a pretty big change internally, and includes a few features that we are actively testing. We are currently on 5.0.0-beta2, with at least a few more expected before a release candidate. We've been using 5.0 in production for quite a while, and consider it safe to use.

Note that beta2 enables a new feature by default (though for most users, it will be deactivated during config validation).
