### ISSUE TITLE
undefined method `instrument' for ActionView::TemplateRenderer with skylight 4.3.1 and rails 6.1.0.rc1

### ISSUE THREAD

**Issue by EverybodyKurts** [skylightio/skylight-ruby#161]
Testing out rails 6.1.0.rc1 and immediately hit this error with Skylight 4.3.1:

https://github.com/skylightio/skylight-ruby/blob/47f370c55258c4972d7bccded2d3cc220c395179/skylight-core/lib/skylight/core/probes/action_view.rb#L30

```bash
undefined method `instrument' for #<ActionView::TemplateRenderer:0x00007fd3e5d12638> excluded from capture: DSN not set
  
NoMethodError (undefined method `instrument' for #<ActionView::TemplateRenderer:0x00007fd3e5d12638>):
  
skylight-core (4.3.1) lib/skylight/core/probes/action_view.rb:30:in `render_with_layout'
```

**Comment by zvkemp** [comment]
Hi @EverybodyKurts , this issue has been fixed on the current master branch and in the 5.0 beta versions (latest is https://rubygems.org/gems/skylight/versions/5.0.0.beta3).
