### ISSUE TITLE
connection_config deprecation in Rails 6.2

### ISSUE THREAD

**Issue by tisba** [skylightio/skylight-ruby#173]
I just stumbled across multiple gems triggering a deprecation warning in Rails 6.1.2.1, skylight being one of them.

It looks like the cause is already addressed in master, but I missed a entry in the change log for the upcoming release:

```
DEPRECATION WARNING: connection_config is deprecated and will be removed from Rails 6.2 (Use connection_db_config instead) (called from process_heartbeat! at /app/app/models/server.rb:268)
/usr/local/bundle/gems/skylight-core-4.3.2/lib/skylight/core/normalizers/active_record/sql.rb:20:in `normalize'
[…]
```

Maybe it's worth checking that this was addressed and if so, IMO it should be added to change log for the upcoming version.

**Comment by wagenet** [comment]
@tisba we've corrected this in the 5.0 beta. Thanks!

**Comment by tisba** [comment]
Hey @wagenet 👋 Thx for the 5.0 release. Just wanted to let you know, that there is no changelog entry regarding the fix. I have not checked if it is actually fixed, but if it is, it's worth mentioning (I think).

**Comment by zvkemp** [comment]
Hi @tisba! The area where we were previously checking the connection config was removed entirely prior to the method being deprecated (the 5.0 branch has been in progress for quite a while). Since the fix was incidental, it doesn't appear in the changelog.
