### ISSUE TITLE
 RuntimeError("could not submit trace to instrumenter", Some("err=instrumenter not running")), silenced: false }

### ISSUE THREAD

**Issue by Shehbaz** [skylightio/skylight-ruby#175]
Hi,
We experienced a service outage where all of our sidekiq jobs were hanging. On investigation, we found that all of the daemons are healthy but stuck and we found the following error in all logs:

`[SKYLIGHT] internal error: SkError { kind: RuntimeError("could not submit trace to instrumenter", Some("err=instrumenter not running")), silenced: false }`

I could not find any documentation or help on this. My opinion is, skylight agent was unable to submit information due to connection or some internal server error on the skylight side and was throwing runtime error. But I want to understand if this is indeed the case or there is something at our end which made skylight throw this error.

We are using Skylight for many years now and this is the first time we have seen this case.

**Comment by wagenet** [comment]
@Shehbaz my apologies for the delay here. (We're generally faster responding to direct support queries via the in-app messenger.)

There's nothing in the Skylight code that actually waits for a successful response from this method so it seems unlikely that it would be the cause of your server hanging. It seems more likely to me that there was something that caused both the sidekiq hanging and the crash of the Skylight instrumenter.

However, please do reach out to us if you continue to have issues!
