### ISSUE TITLE
Feature Request: specify SKYLIGHT_IGNORED_ENDPOINT by URL

### ISSUE THREAD

**Issue by ruckus** [skylightio/skylight-ruby#19]
I was super excited to see support for `SKYLIGHT_IGNORED_ENDPOINT` - thank you.

However, I've implemented my health-check as Rails middleware just because I was sick of seeing my logs filled with the health checks, ala;

`config.middleware.insert_before Rails::Rack::Logger, "HealthCheckMiddleware"`

Anyways, due to this invocation style I don't have a `controller#action` pair to specify to the env var.

My request: allow one to specify a URL ala `/health-check` and not just a `controller#action` pair.

**Comment by felixbuenemann** [comment]
I think a flexible option would be a lambda given to config.skylight that get's the rack request passed in. That way it would be easy to ignore certain request paths or user agents.

**Comment by teodor-pripoae** [comment]
I think you can do something like this in your middleware:

```ruby
def call(env)
  if env['PATH_INFO'] == '/ping'
    trace = Skylight::Instrumenter.instance.try(:current_trace)

    if trace
      trace.endpoint = "healthcheck"
    end

    [200, [], "ok"]
  else
    @app.call(env)
  end
end
```

And then add `healthcheck` to ignored endpoints.

**Comment by elitau** [comment]
I've written a small [rack middleware](https://rubygems.org/gems/rack-skylight-endpoint) based on @teodor-pripoae code which can be used until the option becomes more customizable.

**Comment by wagenet** [comment]
As of 1.4.0-beta.2 we now instrument Middleware separately in Rails. If they handle the request it will be named after the Middleware and not just called Rack. I think this resolves this issue, but let me know if I'm missing something.
