### ISSUE TITLE
ERROR:skylight::cli: skylightd exiting abnormally

### ISSUE THREAD

**Issue by andruby** [skylightio/skylight-ruby#21]
I'm trying out Skylight and running it on a Thin cluster with 3 thin processes. The agent is enabled but is not sending out any data. 

I'm getting these errors in my **log/thin.x.log** files:

```
ERROR:skylight::cli: skylightd exiting abnormally; err=unable to bind UDS server; err=invalid argument (path must be smaller than SUN_LEN)
ERROR:skylight::ipc::client: could not send message to daemon; err=unable to spawn daemon -- timed out; timeout=5s
ERROR:skylight::c_api: Skylight instrumenter failed to submit trace; err=InternalClientError
```

The **log/production.log** shows skylight as enabled:

```
I, [2014-12-19T11:59:04.109040 #27279]  INFO -- : [SKYLIGHT] [0.5.2] Skylight agent enabled
```

The **log/skylight.log** file repeats this line a bunch of times:

```
W, [2014-12-19T12:01:31.073807 #27219]  WARN -- : [SKYLIGHT] [0.5.2] failed to submit trace to worker; err=native Instrumenter#submit_trace failed
```

**Comment by p8** [comment]
And it should be the following in later versions of skylight:
    daemon:
      sockdir_path: /tmp/my-app-name

**Comment by giedriusr** [comment]
Hello,

I've recently tried to install skylight and deploy our app to production. Config file has been generated by skylight with auth token. On starting the server we got an error:

ERROR:skylight::cli: skylightd exiting abnormally; err=DaemonLockFailed
```
 skylight (0.10.4)
```

Any suggestions? Is it because of the wrong config yml as stated above?

**Comment by wagenet** [comment]
@giedriusr Can you contact us via the "?" button in the web UI or email support@skylight.io? Thanks!

**Comment by giedriusr** [comment]
@wagenet done.
