### ISSUE TITLE
Can't seem to override pidfile_path

### ISSUE THREAD

**Issue by p8** [skylightio/skylight-ruby#22]
Is see the following error in my log:

     [SKYLIGHT] [0.6.0-beta.1] File `/home/app/releases/20150106201439/tmp/skylight.pid` not writable.  Please set daemon.pidfile_path or daemon.sockdir_path in your config to a writable path; disabling Skylight agent

I've tried the following but the pidfile_path won't be overriden:

     daemon.pidfile_path: /home/app/shared/tmp/pids/skylight.pid

Or:

    daemon:
       pidfile_path: /home/app/shared/tmp/pids/skylight.pid

**Comment by wagenet** [comment]
Hmm, this doesn't seem good. Did you also try setting `sockfile_path`?

**Comment by p8** [comment]
Aargh, I had an extra '---' in my yaml file which caused the problem.
Sorry for the inconvenience.

**Comment by wagenet** [comment]
@p8 No problem. Glad you got it sorted out :)
