### ISSUE TITLE
gem install skylight on mac fails with reference to /users/mpapis

### ISSUE THREAD

**Issue by technomage** [skylightio/skylight-ruby#27]
Attempting to install the skylight gem 0.6.0 on mac references a hard coded directory

linking shared-object skylight_native.bundle
ld: warning: directory not found for option '-L/Users/mpapis/.sm/pkg/active/lib'
ld: targeted OS version does not support use of thread local variables in _sky_increment_allocation for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [skylight_native.bundle] Error 1

**Comment by technomage** [comment]
This was with MRI Ruby 2.1.5 and Xcode 6.1.1

**Comment by carllerche** [comment]
Hi, sorry about this. We do not have any hard coded directories in our install process. I would guess that this is an artifact of the RVM you are using (given that mpapis is the RVM author). However, I don't think that the warning is related to the error that you are seeing. What version of OS X are you on?

**Comment by technomage** [comment]
Yosemite 10.10.2

**Comment by technomage** [comment]
Here is the full output from gem install skylight

Building native extensions.  This could take a while...
ERROR:  Error installing skylight:
	ERROR: Failed to build gem native extension.

    /Users/lattam/.rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20150226-33644-o165ea.rb extconf.rb
I, [2015-02-26T15:49:12.088334 #33647]  INFO -- : SKYLIGHT_HDR_PATH=/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.0/ext; SKYLIGHT_LIB_PATH=/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.0/lib/skylight/native/x86_64-darwin
I, [2015-02-26T15:49:12.088883 #33647]  INFO -- : [SKYLIGHT] fetching native ext; curr-platform=x86_64-darwin; requested-arch=x86_64-darwin; version=0.5.0-fbaa3ed
I, [2015-02-26T15:49:12.089037 #33647]  INFO -- : [SKYLIGHT] attempting to fetch from remote; uri=https://s3.amazonaws.com/skylight-agent-packages/skylight-native/0.5.0-fbaa3ed/skylight_x86_64-darwin.tar.gz
I, [2015-02-26T15:49:16.071115 #33647]  INFO -- : [SKYLIGHT] successfully downloaded native ext; out=/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.0/ext/skylight_x86_64-darwin.tar.gz
x skylightd
x libskylight.dylib
x skylight.h
x skylight_dlopen.h
x skylight_dlopen.c
checking for skylight_dlopen.h in /Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.0/ext... yes
checking for dlfcn.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for fast thread local storage... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling skylight_dlopen.c
compiling skylight_memprof.c
compiling skylight_native.c
linking shared-object skylight_native.bundle
ld: warning: directory not found for option '-L/Users/mpapis/.sm/pkg/active/lib'
ld: targeted OS version does not support use of thread local variables in _sky_increment_allocation for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [skylight_native.bundle] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.0 for inspection.
Results logged to /Users/lattam/.rvm/gems/ruby-2.1.5@vip/extensions/x86_64-darwin-14/2.1.0-static/skylight-0.6.0/gem_make.out

**Comment by halorgium** [comment]
Could you send us all the files in the `/Users/lattam/.rvm/gems/ruby-2.1.5@vip/extensions/x86_64-darwin-14/2.1.0-static/skylight-0.6.0` directory?

**Comment by technomage** [comment]
Here is the verbose gem install and the log files from the directories for 0.6.1.  Just getting back to this project.  The error seems to be detection of whether thread local storage is supported.  LD indicates it is not, but make thinks it is.

MBP:vipassana lattam$ gem install --verbose skylight -v '0.6.1'
HEAD http://gems.github.com/api/v1/dependencies
404 Not Found
GET http://gems.github.com/prerelease_specs.4.8.gz
304 Not Modified
GET http://gems.github.com/specs.4.8.gz
304 Not Modified
HEAD http://api.rubygems.org/api/v1/dependencies
200 OK
GET http://api.rubygems.org/api/v1/dependencies?gems=skylight
200 OK
GET http://api.rubygems.org/api/v1/dependencies?gems=activesupport
200 OK
GET http://api.rubygems.org/api/v1/dependencies?gems=i18n,json,minitest,thread_safe,tzinfo
200 OK
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/CHANGELOG.md
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/CLA.md
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/CONTRIBUTING.md
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/LICENSE.md
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/README.md
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/bin/skylight
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/ext/extconf.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/ext/libskylight.yml
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/ext/skylight_memprof.c
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/ext/skylight_native.c
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/ext/skylight_native.h
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/api.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/cli.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/compat.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/config.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/core.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/data/cacert.pem
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/formatters/http.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/gc.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/helpers.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/instrumenter.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/middleware.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/native.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/action_controller/process_action.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/action_controller/send_file.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/action_view/render_collection.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/action_view/render_partial.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/action_view/render_template.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/active_record/sql.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/active_support/cache.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/active_support/cache_clear.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/active_support/cache_decrement.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/active_support/cache_delete.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/active_support/cache_exist.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/active_support/cache_fetch_hit.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/active_support/cache_generate.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/active_support/cache_increment.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/active_support/cache_read.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/active_support/cache_read_multi.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/active_support/cache_write.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/default.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/normalizers/moped/query.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/probes.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/probes/excon.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/probes/excon/middleware.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/probes/net_http.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/probes/redis.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/probes/sequel.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/probes/sinatra.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/probes/tilt.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/railtie.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/sinatra.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/subscriber.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/trace.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/util.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/util/allocation_free.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/util/clock.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/util/gzip.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/util/hostname.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/util/http.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/util/inflector.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/util/logging.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/util/multi_io.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/util/native_ext_fetcher.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/util/platform.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/util/ssl.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/active_support/notifications.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/active_support/notifications/fanout.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/active_support/notifications/instrumenter.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/active_support/per_thread_registry.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/highline.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/highline/color_scheme.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/highline/compatibility.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/highline/import.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/highline/menu.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/highline/question.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/highline/simulate.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/highline/string_extensions.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/highline/style.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/highline/system_extensions.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/actions.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/actions/create_file.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/actions/create_link.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/actions/directory.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/actions/empty_directory.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/actions/file_manipulation.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/actions/inject_into_file.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/base.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/command.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/core_ext/hash_with_indifferent_access.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/core_ext/io_binary_read.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/core_ext/ordered_hash.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/error.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/group.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/invocation.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/parser.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/parser/argument.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/parser/arguments.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/parser/option.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/parser/options.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/rake_compat.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/runner.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/shell.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/shell/basic.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/shell/color.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/shell/html.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/util.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/cli/thor/version.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/thread_safe.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/thread_safe/non_concurrent_cache_backend.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vendor/thread_safe/synchronized_cache_backend.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/version.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/vm/gc.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/sql_lexer.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/sql_lexer/lexer.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/sql_lexer/string_scanner.rb
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/sql_lexer/version.rb
Building native extensions.  This could take a while...
/Users/lattam/.rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20150703-25992-1q23qr1.rb extconf.rb
/Users/lattam/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:70: warning: Insecure world writable dir /usr/local/git/bin in PATH, mode 040757
I, [2015-07-03T10:06:08.351630 #25993]  INFO -- : SKYLIGHT_HDR_PATH=/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/ext; SKYLIGHT_LIB_PATH=/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/native/x86_64-darwin
I, [2015-07-03T10:06:08.352035 #25993]  INFO -- : [SKYLIGHT] fetching native ext; curr-platform=x86_64-darwin; requested-arch=x86_64-darwin; version=0.5.0-fbaa3ed
I, [2015-07-03T10:06:08.352180 #25993]  INFO -- : [SKYLIGHT] attempting to fetch from remote; uri=https://s3.amazonaws.com/skylight-agent-packages/skylight-native/0.5.0-fbaa3ed/skylight_x86_64-darwin.tar.gz
I, [2015-07-03T10:06:10.964967 #25993]  INFO -- : [SKYLIGHT] successfully downloaded native ext; out=/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/ext/skylight_x86_64-darwin.tar.gz
/Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/lib/skylight/util/native_ext_fetcher.rb:67: warning: Insecure world writable dir /usr/local/git/bin in PATH, mode 040757
x skylightd
x libskylight.dylib
x skylight.h
x skylight_dlopen.h
x skylight_dlopen.c
checking for skylight_dlopen.h in /Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/ext... yes
checking for dlfcn.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for fast thread local storage... yes
creating Makefile
make "DESTDIR=" clean
make "DESTDIR="
compiling skylight_dlopen.c
compiling skylight_memprof.c
compiling skylight_native.c
linking shared-object skylight_native.bundle
ld: warning: directory not found for option '-L/Users/mpapis/.sm/pkg/active/lib'
ld: targeted OS version does not support use of thread local variables in _sky_increment_allocation for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [skylight_native.bundle] Error 1
ERROR:  Error installing skylight:
	ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
make failed, exit code 2

Gem files will remain installed in /Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1 for inspection.
Results logged to /Users/lattam/.rvm/gems/ruby-2.1.5@vip/extensions/x86_64-darwin-14/2.1.0-static/skylight-0.6.1/gem_make.out
MBP:vipassana lattam$ 

MBP:skylight-0.6.1 lattam$ cat gem_make.out
Building has failed. See above output for more information on the failure.
make failed, exit code 2
MBP:skylight-0.6.1 lattam$ cat mkmf.log
find_header: checking for skylight_dlopen.h in /Users/lattam/.rvm/gems/ruby-2.1.5@vip/gems/skylight-0.6.1/ext... -------------------- yes

"gcc -o conftest -I/Users/lattam/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0/x86_64-darwin14.0 -I/Users/lattam/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0/ruby/backward -I/Users/lattam/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -I/Users/mpapis/.sm/pkg/active/include -fPIC -mmacosx-version-min=10.7 -pipe conftest.c  -L. -L/Users/lattam/.rvm/rubies/ruby-2.1.5/lib -L. -L/Users/mpapis/.sm/pkg/active/lib -fPIC -Bstatic -fstack-protector   -arch x86_64   -lruby-static -framework CoreFoundation  -lpthread -ldl -lobjc "
ld: warning: directory not found for option '-L/Users/mpapis/.sm/pkg/active/lib'
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"gcc -E -I/Users/lattam/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0/x86_64-darwin14.0 -I/Users/lattam/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0/ruby/backward -I/Users/lattam/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -I/Users/mpapis/.sm/pkg/active/include -fPIC -mmacosx-version-min=10.7 -pipe  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <skylight_dlopen.h>
/* end */

--------------------

have_header: checking for dlfcn.h... -------------------- yes

"gcc -E -I/Users/lattam/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0/x86_64-darwin14.0 -I/Users/lattam/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0/ruby/backward -I/Users/lattam/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -I/Users/mpapis/.sm/pkg/active/include -fPIC -mmacosx-version-min=10.7 -pipe  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <dlfcn.h>
/* end */

--------------------

have_func: checking for rb_thread_call_without_gvl() in ruby/thread.h... -------------------- yes

"gcc -o conftest -I/Users/lattam/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0/x86_64-darwin14.0 -I/Users/lattam/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0/ruby/backward -I/Users/lattam/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -I/Users/mpapis/.sm/pkg/active/include -fPIC -mmacosx-version-min=10.7 -pipe conftest.c  -L. -L/Users/lattam/.rvm/rubies/ruby-2.1.5/lib -L. -L/Users/mpapis/.sm/pkg/active/lib -fPIC -Bstatic -fstack-protector   -arch x86_64   -lruby-static -framework CoreFoundation  -lpthread -ldl -lobjc "
ld: warning: directory not found for option '-L/Users/mpapis/.sm/pkg/active/lib'
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <ruby/thread.h>
 4: 
 5: /*top*/
 6: extern int t(void);
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     printf("%p", &t);
11:   }
12: 
13:   return 0;
14: }
15: int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_thread_call_without_gvl; return 0; }
/* end */

--------------------

checking for fast thread local storage... -------------------- yes

"gcc -I/Users/lattam/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0/x86_64-darwin14.0 -I/Users/lattam/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0/ruby/backward -I/Users/lattam/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -I/Users/mpapis/.sm/pkg/active/include -fPIC -mmacosx-version-min=10.7 -pipe -Werror  -arch x86_64  -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: __thread int foo;
/* end */

--------------------

MBP:skylight-0.6.1 lattam$

**Comment by technomage** [comment]
This seems to suggest that OS/X does not support thread local storage with clang from Xcode.

http://stackoverflow.com/questions/23791060/c-thread-local-storage-clang-503-0-40-mac-osx

Looking at the above it looks like your make is using "gcc"? Which gcc do you have installed on macs that this builds on?  Apple has gone completely to clang.

**Comment by technomage** [comment]
My current gcc is:

MBP:skylight-0.6.1 lattam$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

**Comment by wagenet** [comment]
@technomage sorry for such a delayed response here. I'm going to close this ticket for now but if you still have issues with the latest agent, please let us know.

Also, you'll get much quicker support by emailing support@skylight.io or using the "?" button in the app UI.
