### ISSUE TITLE
skylight 5.0 breaks in combination with other net/http instrumentation

### ISSUE THREAD

**Issue by tisba** [skylightio/skylight-ruby#292]
We just saw an issue that the latest skylight release (5.0) causes an infinite loop and eventual "stack level too deep" error when used with `rack-mini-profiler`.

Reverting to skylight 4.3.2 for now fixed the issue. Currently we are still investigating and will add more info/context here. ~Sorry for the noise in case it's a rack-mini-profiler (or even our internal) issue.~ I just wanted to make sure people get a heads up.

Here is a slice of the stack that loops:
```
[…]
/app/shared/bundle/ruby/2.7.0/gems/skylight-5.0.0/lib/skylight/probes/net_http.rb:26:in `request'
/app/shared/bundle/ruby/2.7.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:19:in `block in request_with_mini_profiler'
/app/shared/bundle/ruby/2.7.0/gems/rack-mini-profiler-2.3.1/lib/mini_profiler/profiling_methods.rb:46:in `step'
/app/shared/bundle/ruby/2.7.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:18:in `request_with_mini_profiler'
/app/shared/bundle/ruby/2.7.0/gems/skylight-5.0.0/lib/skylight/probes/net_http.rb:26:in `block in request'
/app/shared/bundle/ruby/2.7.0/gems/skylight-5.0.0/lib/skylight/instrumenter.rb:261:in `instrument'
/app/shared/bundle/ruby/2.7.0/gems/skylight-5.0.0/lib/skylight.rb:208:in `instrument'
/app/shared/bundle/ruby/2.7.0/gems/skylight-5.0.0/lib/skylight/probes/net_http.rb:26:in `request'
[…]
```

The problem seems to be, that skylight 5.0 is no longer aliasing `Net::HTTP#request` to `request_without_sk`and using it. Instead only `super` is called, which causes the call to enter a loop. As a result, no other instrumentation or "patching" of net/http is currently possible with skylight 5.0.

**Comment by tisba** [comment]
I believe the old behaviour was more robust and cleaner (as clean as monkey patching can be 😀). The conflict with `rack-mini-profiler` might be a strange use case, but IMO monkey patches such be as safe as possible regardless.

I'm happy to provide more context or propose a solution.

**Comment by wagenet** [comment]
@tisba sorry for the trouble! In general, using `prepend` with `super` is the preferred way to do these sorts of things. It looks like rack-mini-profiler can do prepend as well if configured to do so: https://github.com/MiniProfiler/rack-mini-profiler/blob/93e0b5e25f5cd58a3acb92cae016a5cca98ee265/lib/patches/net_patches.rb. Are you able to try this?

**Comment by wagenet** [comment]
@tisba no worries, this area is a bit messy. We were first motivated to change to prepend because we started having issues with interoperability with other libraries that were using it first! I think prepend is objectively better, but it's very annoying that it doesn't play well with alias method chaining. @wycats (one of our founders) actually was part of the proposal for `prepend` but he said he would have done things differently if he'd realized that there would be these sorts of issues!

**Comment by tisba** [comment]
Thank you @wagenet!

Adjusting this in our `Gemfile` solved the issue:

```ruby
gem "rack-mini-profiler", require: ["prepend_net_http_patch"]
```

What a mess! 😄
