### ISSUE TITLE
Does config.skylight.logger get ignored?

### ISSUE THREAD

**Issue by pogopaule** [skylightio/skylight-ruby#31]
Hi!

I followed the [instructions on how to change the logger](https://docs.skylight.io/agent/#railtie)
But it seems that `config.skylight.logger` is ignored.

    # config/application.rb
    skylightLogger = LogStashLogger.new(type: :file, path: File.join(Rails.root, 'log', 'skylight.log'), sync: true)
    skylightLogger.warn 'I am a test'
    config.skylight.logger = skylightLogger

    # log/skylight.log
    {"message":"I am a test","@timestamp":"2015-05-05T12:05:52.874+02:00","@version":"1","severity":"WARN","host":"vagrant-debian-wheezy"}
    W, [2015-05-05T12:05:53.464793 #9370]  WARN -- : [SKYLIGHT] [0.6.0] Running Skylight in development mode. No data will be reported until you deploy your app.
    (To disable this message, set `alert_log_file` in your config.)

**Comment by wagenet** [comment]
@pogopaule Sorry for the very delayed reply here. For quickest support contact us at support@skylight.io or via the "?" button in the app UI.

Is your concern here that the development mode warning is not correctly formatted? This has to do with how we handle the `alert_log_file`. If you set your `alert_log_file` in the configuration to another path, then it should work as expected.

Let me know if you still have trouble.
