### ISSUE TITLE
Deprecated Psych.safe_load arguments

### ISSUE THREAD

**Issue by semaperepelitsa** [skylightio/skylight-ruby#325]
When running Ruby in verbose mode `$VERBOSE = true`

> .bundle/ruby/2.7.0/gems/skylight-core-4.3.2/lib/skylight/core/config.rb:135: Passing permitted_classes with the 2nd argument of Psych.safe_load is deprecated. Use keyword argument like Psych.safe_load(yaml, permitted_classes: ...) instead.
> .bundle/ruby/2.7.0/gems/skylight-core-4.3.2/lib/skylight/core/config.rb:135: Passing permitted_symbols with the 3rd argument of Psych.safe_load is deprecated. Use keyword argument like Psych.safe_load(yaml, permitted_symbols: ...) instead.
> .bundle/ruby/2.7.0/gems/skylight-core-4.3.2/lib/skylight/core/config.rb:135: Passing aliases with the 4th argument of Psych.safe_load is deprecated. Use keyword argument like Psych.safe_load(yaml, aliases: ...) instead.

**Comment by wagenet** [comment]
Thanks for bringing this to our attention. I'll look into it.

**Comment by wagenet** [comment]
@semaperepelitsa the fix for this should come out in Skylight 5.1.

**Comment by zvkemp** [comment]
@semaperepelitsa Skylight 5.1.0.beta has been released, which includes @wagenet's fix for this issue.
