### ISSUE TITLE
Skylight 5.0.x appears to require GLIBC 2.18

### ISSUE THREAD

**Issue by rdunlop** [skylightio/skylight-ruby#331]
I'm having troubles getting skylight 5.0.x to run on our servers which run skylight 4.3.2 without issue.

We appear to satisfy the requirements:
- Rails 5.2.5
- Glibc 2.17
```
/lib64/libc.so.6 --version
GNU C Library (GNU libc) stable release version 2.17, by Roland McGrath et al.
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.8.5 20150623 (Red Hat 4.8.5-28).
Compiled on a Linux 3.2.5 system on 2020-02-11.
Available extensions:
	The C stubs add-on version 2.1.2.
	crypt add-on version 2.1 by Michael Glad and others
	GNU Libidn by Simon Josefsson
	Native POSIX Threads Library by Ulrich Drepper et al
	BIND-8.2.3-T5B
	RT using linux kernel aio
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.
```
- ruby 2.6.6

And yet it fails:
```
$ bundle exec skylight doctor 
Checking SSL
  OK

Checking for Rails
  Rails application detected

Checking for native agent
  Unable to load native extension
    Reason unknown


Skylight Doctor found some errors. Please review the output above.
If you have any further questions, please contact support@skylight.io.
```

The install.log doesn't show me anything useful:
```
cat /<redacted>/shared/bundle/ruby/2.6.0/gems/skylight-4.3.2/ext/install.log 
I, [2021-02-12T23:57:42.590069 #24395]  INFO -- : SKYLIGHT_HDR_PATH=/<redacted>/shared/bundle/ruby/2.6.0/gems/skylight-4.3.2/ext; SKYLIGHT_LIB_PATH=/<redacted>/shared/bundle/ruby/2.6.0/gems/skylight-4.3.2/lib/skylight/native/x86_64-linux
I, [2021-02-12T23:57:42.590616 #24395]  INFO -- : [SKYLIGHT] fetching native ext; curr-platform=x86_64-linux; requested-arch=x86_64-linux; version=4.1.0-46806f5
I, [2021-02-12T23:57:42.590785 #24395]  INFO -- : [SKYLIGHT] attempting to fetch from remote; uri=https://s3.amazonaws.com/skylight-agent-packages/skylight-native/4.1.0-46806f5/skylight_x86_64-linux.tar.gz
I, [2021-02-12T23:57:42.677272 #24395]  INFO -- : [SKYLIGHT] successfully downloaded native ext; out=/<redacted>/shared/bundle/ruby/2.6.0/gems/skylight-4.3.2/ext/skylight_x86_64-linux.tar.gz
I, [2021-02-12T23:57:42.800524 #24395]  INFO -- : [SKYLIGHT] tar xzvf /<redacted>/shared/bundle/ruby/2.6.0/gems/skylight-4.3.2/ext/skylight_x86_64-linux.tar.gz
I, [2021-02-12T23:57:42.800591 #24395]  INFO -- : [SKYLIGHT] skylightd
libskylight.so
skylight.h
skylight_dlopen.h
skylight_dlopen.c
```

Digging in further, I've been able to trace it down to (I think)...if I try to execute the libskylight.so, it tries to use GLIBC 2.18...which is not installed on this machine.:
```
ldd <redacted>/shared/bundle/ruby/2.6.0/gems/skylight-5.0.1/lib/skylight/native/x86_64-linux/libskylight.so 
<redacted>/shared/bundle/ruby/2.6.0/gems/skylight-5.0.1/lib/skylight/native/x86_64-linux/libskylight.so: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by <redacted>/shared/bundle/ruby/2.6.0/gems/skylight-5.0.1/lib/skylight/native/x86_64-linux/libskylight.so)
	linux-vdso.so.1 =>  (0x00007ffc15ebc000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f39e138b000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f39e1187000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f39e0f6b000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f39e0c69000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f39e0a53000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f39e0685000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f39e1e82000)
```

I can't troubleshoot this further, because as far as I can tell, the source code for the skylight rust agent binary is closed-source, and thus I cannot tell if there were changes which purposefully updated the glibc requirement, even though the documentation says 2.15+.

Any advise or comments? Thank you

**Comment by wagenet** [comment]
@rdunlop my apologies for the issue here. Unfortunately, the docs here are outdated and I actually have an internal PR to update them. Currently, our builds are done on a docker image with glibc 2.23. Depending on the symbols used it may be that as low as 2.18 works, though I've not been able to test it. You may have success with an older version of Skylight.

By the way, can I ask what Linux distro you're running?

**Comment by rdunlop** [comment]
We are running on Amazon Linux AMI
https://aws.amazon.com/amazon-linux-ami/2018.03-release-notes/.

We are aware that this is no longer supported by AWS, we're working on moving off, onto AWS Linux AMI 2, but haven't finished this yet.

I would consider this to be a "breaking change" which should have been published in the changelog, no? Perhaps you can go add it there now?

We will pin our version to 4.2.3, though I will grumble about this greatly.

**Comment by rdunlop** [comment]
I opened https://github.com/skylightio/skylight-ruby/pull/332 for you

**Comment by wagenet** [comment]
Whoops, I missed that you opened that. My apologies for the oversight here. We definitely should have marked this as a breaking change.

**Comment by wagenet** [comment]
I've updated the README here and the docs change will be deployed shortly: https://github.com/skylightio/skylight-ruby/commit/2e4d8d676a2ffde0902b2be00a2f6dd96cbc564d
