### ISSUE TITLE
skylightd causes process leak

### ISSUE THREAD

**Issue by bronson** [skylightio/skylight-ruby#34]
When I include skylight in my Gemfile, every fork creates a zombie process until my VPS runs out of memory.  When I omit it, everything is fine.

My app calls fork to render a PDF:

```ruby
        pid = fork do
          kit = PDFKit.new(@url, args)
          kit.to_file("#{path}.pending")
          # it's OK if another request has already deleted the file
          File.rename("#{path}.pending", path) rescue Errno::ENOENT
        end
        Process.detach(pid)
```

This is called in a rake task, using an integration session to fake a request.  Here's a backtrace from a stuck process:

```
	from /home/property-build/.gem/ruby/2.0.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
	from /home/property-build/.gem/ruby/2.0.0/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
	from /home/property-build/.gem/ruby/2.0.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action'
	from /home/property-build/.gem/ruby/2.0.0/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
	from /home/property-build/propertysearch/app/controllers/pdf_controller.rb:9:in `generate'
	from /home/property-build/propertysearch/app/generators/pdf_generator.rb:38:in `generate'
	from /home/property-build/propertysearch/app/generators/pdf_generator.rb:38:in `fork'
	from /home/property-build/.gem/ruby/2.0.0/gems/skylight-0.6.0/lib/skylight/instrumenter.rb:68:in `block in <class:Instrumenter>'
	from /home/property-build/.gem/ruby/2.0.0/gems/skylight-0.6.0/lib/skylight/instrumenter.rb:50:in `stop!'
	from /home/property-build/.gem/ruby/2.0.0/gems/skylight-0.6.0/lib/skylight/instrumenter.rb:50:in `synchronize'
	from /home/property-build/.gem/ruby/2.0.0/gems/skylight-0.6.0/lib/skylight/instrumenter.rb:55:in `block in stop!'
	from /home/property-build/.gem/ruby/2.0.0/gems/skylight-0.6.0/lib/skylight/instrumenter.rb:138:in `shutdown'
	from /home/property-build/.gem/ruby/2.0.0/gems/skylight-0.6.0/lib/skylight/instrumenter.rb:138:in `native_stop'
```

This is with version 0.6.0.

**Comment by bronson** [comment]
Interesting...  I'm launching rails/unicorn from systemd.  I used to have to kill unicorn hard before calling systemd restart, otherwise the systemd restart could hang.  I always figured it was a systemd problem.

Without skylight, systemd restart seems to work 100% of the time now.

**Comment by wycats** [comment]
@bronson We're investigating this as we speak. One of the things that throws a bit of a monkey-wrench into the works in that the skylightd binary we ship was actually shipped with a version of the Rust compiler from last year. We haven't needed to ship an update yet, and we've been waiting for Rust 1.0 to settle down before finalizing an update and shipping it.

At the moment, our master branch is tracking Rust stable, but there's one issue that we've reported upstream (to Rust) that we're waiting for a resolution on. In the meantime, we'll try to reproduce the issue against the current binary. Once we get the resolution, we'll check to see if it's still reproducible on the stable version of Rust, and take it from there.

Thanks for bearing with us!

**Comment by wagenet** [comment]
@bronson the 0.7 beta series is using the latest Rust nightly. Can you check and see if that resolves your issue?

**Comment by bronson** [comment]
At first glance, this does appear to fix the issue.  I just deployed it...  I don't see the process leak, and systemd appears to be able to restart the app reliably.

I'll leave skylight running for a few days and see what happens.

**Comment by wagenet** [comment]
@bronson, great! I'm going to go ahead and close this issue, but please do let me know if you encounter any further issues.
