### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by adamdebono** [skylightio/skylight-ruby#363]
I've been seeing our servers periodically fail due to segmentation faults. I'm not certain that the Skylight gem is at fault, but it does appear to be triggering them.

Here's a couple examples, I have seen others.
```
EVENTS	1626909684304	/usr/local/bundle/gems/skylight-5.1.1/lib/skylight/subscriber.rb:97: [BUG] object allocation during garbage collection phase	1626909683900
EVENTS	1626909684304	ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-musl]	1626909683900
```
```
EVENTS	1626907699089	/usr/local/bundle/gems/skylight-5.1.1/lib/skylight/extensions/source_location.rb:241: [BUG] Segmentation fault at 0x00007f4698057658	1626907695850
EVENTS	1626907699089	ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-musl]	1626907695851
```

I have never seen this happen in our development environments - and the skylight gem is disabled there - although it could also be related to a difference in our production stack.

Our stack is:
- AWS ECS Fargate, 0.5cpu, 1gb ram per container
- Alpine Linux 3.13
- Ruby 2.7.2
- Rails 6.1.32

I'd appreciate any help or advice.

**Comment by wagenet** [comment]
In case anyone stumbles across this, I just want to note that we resolved this issue directly with the customer. It turned out not to be an issue with Skylight.
