### ISSUE TITLE
Middleware thread safey

### ISSUE THREAD

**Issue by jnimety** [skylightio/skylight-ruby#366]
Hello. It is my understanding that setting instance variables in Rack Middleware `call` is not thread safe. It may not be a serious issue but I did notice that you set  `@current_request_id` during `call` in https://github.com/skylightio/skylight-ruby/blob/master/lib/skylight/middleware.rb#L127

Here are some older references about Rack, call, and instance variables:

https://stackoverflow.com/questions/23028226/rack-middleware-and-thread-safety
https://github.com/pdfkit/pdfkit/issues/358

**Comment by zvkemp** [comment]
Hi @jnimety, thanks for the report! You are correct, we shouldn't set an instance variable in that context. I'll correct this shortly.

**Comment by wagenet** [comment]
Resolved by 53a60ccbfc903a4d0c87126655b9867188963d8e
