### ISSUE TITLE
Delete old releases

### ISSUE THREAD

**Issue by sandstrom** [skylightio/skylight-ruby#379]
Since you aren't using releases, cleaning up the two that exist would make it easier to track progress.

https://github.com/skylightio/skylight-ruby/releases

Right now that page give the false impression that  v3.1.0-beta2 is the latest version.

**Comment by chancancode** [comment]
Sure, I have deleted it. We could probably update the publishing scripts to actually do that too, but this is an improvement for now. Thanks for catching it!
