### ISSUE TITLE
Undefined method `safe_constantize'

### ISSUE THREAD

**Issue by juanmanuelramallo** [skylightio/skylight-ruby#381]
## Steps to reproduce
1. Using a Rails 7 application
1. Add `gem "skylight"` in the Gemfile
1. Run `bundle install`
1. Latest gem version is installed v5.1.1
1. Run the app

## Expected
No error is logged

## Actual
The following error is logged
```
Skylight: Subscriber#start error; msg=undefined method `safe_constantize' for ActiveSupport::Dependencies:Module
```

## Notes
Looks like https://github.com/skylightio/skylight-ruby/compare/v5.1.1...v5.2.0-beta2#diff-63a9a380428bd5129f3c467d0de5b75eb9d528059034c08bb02f03a166d0048dR166 is needed in order to properly work with Rails 7. This is because AS::Dependencies#safe_constantize was removed in Rails 7.0.0.alpha1 https://github.com/rails/rails/commit/38e82daee81e1447d1e66ce7d5fe733ecbbc27d5#diff-ba884c931e36571626f3a271c37fe6fae7bbcbbf0e82d515213f99552704ef53

```diff
-          if (constant = ::ActiveSupport::Dependencies.safe_constantize(constant_name))
+          if (constant = ::ActiveSupport::Inflector.safe_constantize(constant_name))
```

**Comment by wagenet** [comment]
Thanks for the reminder. We’ll have a final release out soon!
