### ISSUE TITLE
ERB variables are not interpolated in config/skylight.yml

### ISSUE THREAD

**Issue by thejchap** [skylightio/skylight-ruby#45]
Still investigating, but here are my findings so far. Please let me know if I'm missing something:

The reason we have gone this route is that we currently have two Skylight-enabled apps on the same box in the same env, hence we need to have separate auth tokens and can't just set `SKYLIGHT_AUTHENTICATION`

```
$ cat config/skylight.yml
---
# The authentication token for the application.
authentication: <%= ENV['SOME_OTHER_ENV_VARIABLE_WITH_TOKEN'] %>
```

```rb
# lib/skylight/railtie.rb

require 'skylight'
require 'rails'

module Skylight
  class Railtie < Rails::Railtie
    # ...

    config = load_skylight_config(app)
    Rails.logger.info config.inspect #=> #<Skylight::Config:0x007f98c0f88a30 @values={:authentication=>"<%= ENV['SOME_OTHER_ENV_VARIABLE_WITH_TOKEN'] %>", ...>

    # ...
  end
end
```

**Comment by thejchap** [comment]
Just found https://github.com/skylightio/skylight-ruby/issues/28. Sorry! :+1:

**Comment by wagenet** [comment]
@thejchap no problem. It will be a part of 0.8.0 which should go out this week.
