### ISSUE TITLE
Incompatibility with GraphQL-Ruby 2.0.18+ out-of-the-box

### ISSUE THREAD

**Issue by swrobel** [skylightio/skylight-ruby#460]
It seems there was a [breaking change](https://github.com/rmosolgo/graphql-ruby/pull/4344) introduced in graphql-ruby 2.0.18 that prevents traces from showing the GraphQL operation name, unless a [workaround](https://github.com/MITLibraries/timdex/commit/86ece7741ab3984f50ebdfb31e95fd5675b2f999#diff-c50b52405d9822a0058b890513c04ed8dc9c414cc7cd90cb1b2468dc559ef878R3) is used to enable the legacy tracing API. Below is what our traces looked like with graphql-ruby 2.0.21 before we added the workaround
<img width="1049" alt="Screenshot 2023-05-01 at 6 32 43 PM" src="https://user-images.githubusercontent.com/157270/235560890-2294a537-18be-4a75-bfa0-2d57ee704a97.png">
and after (back to prior behavior, as expected):
<img width="1057" alt="Screenshot 2023-05-01 at 6 35 59 PM" src="https://user-images.githubusercontent.com/157270/235561063-acbe7d13-33a8-47ab-ad01-1e585f988ae7.png">
This gem should be updated to work with graphql-ruby out-of-the box as this workaround isn't very discoverable. I also noticed it's currently causing [failures in your suite](https://github.com/skylightio/skylight-ruby/actions/runs/4722112056/jobs/8376261913#step:8:167) for recent builds where the [latest graphql-ruby is being picked up](https://github.com/skylightio/skylight-ruby/actions/runs/4722112056/jobs/8376261913#step:7:76).

**Comment by swrobel** [comment]
Thanks @zvkemp! Is there any advantage or disadvantage to the workaround you proposed versus the [workaround](https://github.com/MITLibraries/timdex/commit/86ece7741ab3984f50ebdfb31e95fd5675b2f999#diff-c50b52405d9822a0058b890513c04ed8dc9c414cc7cd90cb1b2468dc559ef878R3) I linked to in my OP?

**Comment by zvkemp** [comment]
@swrobel there isn't really a disadvantage per se, but the legacy trace classes in graphql aren't likely to be updated and may be removed in future versions.

In any case, Skylight 6.0.0-beta2 should work correctly with newer GraphQL versions (https://github.com/skylightio/skylight-ruby/commit/459f19219cbabc8caf1110acf029a0c7d37f5037).
