### ISSUE TITLE
failed to instrument span; msg=native Trace#start_span failed

### ISSUE THREAD

**Issue by airblade** [skylightio/skylight-ruby#48]
I'm using skylight-ruby v0.6.1 and Rails 3.2.  My skylight.log is full of:

```
[SKYLIGHT] [0.6.1] native Trace#start_span failed
[SKYLIGHT] [0.6.1] native Trace#start_span failed
[SKYLIGHT] [0.6.1] native Trace#start_span failed
[SKYLIGHT] [0.6.1] failed to instrument span; msg=native Trace#start_span failed
[SKYLIGHT] [0.6.1] failed to instrument span; msg=native Trace#start_span failed
[SKYLIGHT] [0.6.1] failed to instrument span; msg=native Trace#start_span failed
[SKYLIGHT] [0.6.1] failed to instrument span; msg=native Trace#start_span failed
[SKYLIGHT] [0.6.1] failed to instrument span; msg=native Trace#start_span failed
[SKYLIGHT] [0.6.1] failed to instrument span; msg=native Trace#start_span failed
[SKYLIGHT] [0.6.1] failed to instrument span; msg=native Trace#start_span failed
```

My application code looks like:

``` ruby
class Foo
  def trace(name, &block)
    Skylight.instrument(title: name) do
      yield
    end
  end

  def bar
    trace('do something') { do_something }
  end
end
```

What am I doing wrong?

**Comment by i-am-jd** [comment]
Same problem here, using Rails 3.2 as well (3.2.22 to be precise).

**Comment by airblade** [comment]
I still have this problem.  I've been on Skylight 0.10.2 for a while.

**Comment by wagenet** [comment]
This error happens when we've hit the limit for how many spans we instrument in a single request. The current limit is 1024, but we've talked about doubling it. I suspect this will happen soon. That said, we should definitely handle the failure case more elegantly. It's on our radar and we hope to devote some time to it soon.

**Comment by thilonel** [comment]
`[SKYLIGHT] [1.0.0] failed to instrument span; msg=native Trace#start_span failed`

Still around. Please fix it! :)

**Comment by hojberg** [comment]
@wagenet anyway to configure this at least? To up the max num spans

**Comment by faizalzakaria** [comment]
Do we have plan to fix this ?

**Comment by wagenet** [comment]
Unfortunately, we've been delayed on resolving this. I'll try to reprioritize.

**Comment by wagenet** [comment]
I just released version 1.4.0-beta which doubles the limit. Let me know if that helps at all. Depending on just how high your number of spans are it may not resolve it for you, but it's worth a try.

**Comment by lookageek** [comment]
Hitting the 2048 limit too.
```
ERROR:skylight::c_api: failed to start tracing span; err="Exceeded maximum number of trace spans; MAX=2048"
[SKYLIGHT] internal error: failed to start tracing span
```
Can we configure this number? If yes how to even come up with a number that is specific to each app?

**Comment by wagenet** [comment]
@lookageek it's a number we've set on our end to avoid overloading our systems with a badly behaved endpoint. We'll probably up it again in the future but we need to make sure we can handle any extra load. What sort of work are you doing in the endpoint? I assume a complex loop?

**Comment by piotrze** [comment]
@wagenet We hitting this limit too(app is quite big), does it mean when we hit this error the request will not be stored in skylight?

**Comment by AndrewRayCode** [comment]
Seeing this error too, what is going on? What are the downstream effects of getting this error in our app code?

**Comment by wagenet** [comment]
@AndrewRayCode no downstream effects for your app's operation. However, this may cause some data to not show up in your Skylight UI. Can you reach out to us via the in-app messenger or support@skylight.io?

@piotrze can you also reach out to our support if you're still having trouble?

**Comment by AndrewRayCode** [comment]
Does this mean that skylight won't report on significantly complex Ruby traces (which are the ones we probably want skylight on the most?)
