### ISSUE TITLE
skylight process lock on mysql row

### ISSUE THREAD

**Issue by janvarljen** [skylightio/skylight-ruby#49]
I had a strange issue for few weeks now and finally I located the source of the problem.

Occasionally I start receiving lock timeout errors on my Mysql:

    Mysql2::Error: Lock wait timeout exceeded; try restarting transaction: UPDATE `billing_points` SET `last_work_session_id` = 126545, `updated_at` = '2015-10-13 22:13:50' WHERE `billing_points`.`id` = 12016

A simple redeploy of the application would fix the problem but it would reappear in a day or two.

The I started debugging:

with **show processlist;** command  I found that the process locking my table (https://scr.infinum.co/jan_varljen/2015-10-14_00-28-29.png) was actually:

    tcp        0      0 172.31.17.221:44681     172.31.19.34:3306       ESTABLISHED 5743/skylightd

a skylight process running on the server.

I'm using:
rails 4.1.13
skylight 0.8.1
mysql 5.6.23

Do you have any idea why this skylight process is holding the lock?

**Comment by wagenet** [comment]
Thanks for bringing this to our attention. Can you email us at support@skylight.io or use the "?" button in the app UI? Thanks!

**Comment by wagenet** [comment]
For any others interested in this issue, our final correspondence with @janvarljen via email was:

> I talked with one of our other engineers and his current theory is that the mysql gem is not setting the CLOEXEC flag on the socket. However, he didn't have any good ideas on how to validate that hypothesis. All that to say, he's pretty sure that there's a bug in the mysql gem that is causing this issue.

> If you decide to go ahead and file a bug on the gem, let us know and we'll provide the information we have and try to see if we can help get it solved. Sorry I can't give you a fix!
