### ISSUE TITLE
Unintialized Constant Grape::VERSION

### ISSUE THREAD

**Issue by alanjcfs** [skylightio/skylight-ruby#52]
I added only `grape-entity` to the Gemfile (and not `grape`), and Skylight is causing trouble by trying to check for Grape::VERSION, which is only provided by Grape::API and not Grape::Entity.

The following is the error message relevant to Skylight:

    /Users/alan/.gem/ruby/2.2.3/gems/skylight-0.8.1/lib/skylight/probes/grape.rb:6:in `install': uninitialized constant Grape::VERSION (NameError)
        from /Users/alan/.gem/ruby/2.2.3/gems/skylight-0.8.1/lib/skylight/probes.rb:14:in `install'
        from /Users/alan/.gem/ruby/2.2.3/gems/skylight-0.8.1/lib/skylight/probes.rb:35:in `register'
        from /Users/alan/.gem/ruby/2.2.3/gems/skylight-0.8.1/lib/skylight/probes/grape.rb:84:in `<module:Probes>'
        from /Users/alan/.gem/ruby/2.2.3/gems/skylight-0.8.1/lib/skylight/probes/grape.rb:2:in `<module:Skylight>'
        from /Users/alan/.gem/ruby/2.2.3/gems/skylight-0.8.1/lib/skylight/probes/grape.rb:1:in `<top (required)>'
        from /Users/alan/.gem/ruby/2.2.3/gems/skylight-0.8.1/lib/skylight/probes.rb:81:in `require'
        from /Users/alan/.gem/ruby/2.2.3/gems/skylight-0.8.1/lib/skylight/probes.rb:81:in `require'
        from /Users/alan/.gem/ruby/2.2.3/gems/skylight-0.8.1/lib/skylight/railtie.rb:118:in `block in load_probes'
        from /Users/alan/.gem/ruby/2.2.3/gems/skylight-0.8.1/lib/skylight/railtie.rb:117:in `each'
        from /Users/alan/.gem/ruby/2.2.3/gems/skylight-0.8.1/lib/skylight/railtie.rb:117:in `load_probes'
        from /Users/alan/.gem/ruby/2.2.3/gems/skylight-0.8.1/lib/skylight/railtie.rb:22:in `block in <class:Railtie>'
        other unrelated errors...

My investigation shows that these lines https://github.com/skylightio/skylight-ruby/blob/master/lib/skylight/probes.rb#L26-L39 might be problematic because they check for the existence of the Grape constant, which is true for both `grape` and `grape-entity`, and therefore result in probing for Grape::VERSION.

I could add `grape` as a solution, but I'm only using Grape::Entity for the JSON representation. I am okay with a decision to close this issue as a wontfix, but felt that bringing this up with you was important.

**Comment by wagenet** [comment]
Sorry for the trouble here. I think it should be possible to have `grape-entity` not cause issues. I'll investigate more.

**Comment by wagenet** [comment]
In the meantime, you can add this to your application config: `config.skylight.probes -= ['grape']`

**Comment by wagenet** [comment]
@alanjcfs this should be fixed in version 0.9.0 which was just released.

**Comment by alanjcfs** [comment]
Thank you very much :)
