### ISSUE TITLE
Error parsing SQL query on Skylight 0.9.0

### ISSUE THREAD

**Issue by Botje** [skylightio/skylight-ruby#54]
With the new Rust SQL parser, Skylight has started throwing errors like the following:
```
ERROR:skylight::c_api: failed to lex SQL query; err=LexError { kind: UnknownLexError, desc: "unknown sql lex error", pos: 154 }; sql=SELECT COUNT(*) FROM `private_messages` WHERE (((sender_id = 13 AND sender_type = 'Player') OR (receiver_id = 13 AND receiver_type = 'Player'))) AND (NOT EXISTS (SELECT `private_message_reads`.`read_at` FROM `private_message_reads` WHERE `private_message_reads`.`player_id` = 13 AND (private_message_id = private_messages.id)))
```
Here the error points to the `EXISTS` keyword.
```
ERROR:skylight::c_api: failed to lex SQL query; err=LexError { kind: UnknownLexError, desc: "unknown sql lex error", pos: 310 }; sql=SELECT  `venture_advertisements`.* FROM `venture_advertisements` WHERE (credits > 0) AND (`venture_advertisements`.`visual_uid` IS NOT NULL) AND (campaign_started_at < NOW()) AND `venture_advertisements`.`campaign_stopped_at` IS NULL AND (campaign_low_level_budget - campaign_low_level_spent >= 1) AND (id NOT IN (0))  ORDER BY RAND() LIMIT 1
```

Here it points to the `IN` keyword.

**Comment by koenigc** [comment]
Got the same error for this query after update to 0.9.0

```
ERROR:skylight::c_api: failed to lex SQL query; err=LexError { kind: UnknownLexError, desc: "unknown sql lex error", pos: 15 }; 
sql=SELECT  "tours".* FROM "tours"  WHERE "tours"."shuttle_number_id" = $1 AND (departure_date::date = '2015-11-10')  ORDER BY "tours"."id" ASC LIMIT 1 
```

**Comment by wagenet** [comment]
First off, these errors won't actually crash anything. That said there have been some regressions on parsing certain queries. I've been working on fixing some of these and have an internal PR ready with some fixes. I'll examine the queries you've provided and make sure we can parse them too.

For the time being, you can switch back to the Ruby parser by setting `SKYLIGHT_SQL_MODE=ruby` in your environment or `sql_mode: ruby` in your config/skylight.yml.

**Comment by wagenet** [comment]
Ok, so I just reviewed the queries and they're both cases that I've got fixes for! We were failing to handle `NOT` correctly (the first two queries) and we also didn't recognize the typecasting (`::`) syntax. I'm hoping to have fixes for these out today.

**Comment by wagenet** [comment]
We just released version 0.9.1 of the gem which should resolve these issues. Please do let us know if you have more trouble. And, for fastest support, emailing support@skylight.io or using the question mark button in the bottom right of the web UI is recommended.

**Comment by wagenet** [comment]
0.9.1 failed to correct the issues due to incorrectly updating the Rust component. 0.9.2 should resolve this.

**Comment by maebeale** [comment]
I'm getting this error also. I'm thinking it's the COALESCE? And/or SELECT DISTINCT?

ERROR:skylight::c_api: failed to lex SQL query; err=LexError { kind: UnknownLexError, desc: "unknown sql lex error", pos: 25 }; sql=SELECT DISTINCT "tickets".* FROM "tickets" INNER JOIN "ticket_types" ON "ticket_types"."id" = "tickets"."ticket_type_id" INNER JOIN "fests" ON "fests"."id" = "ticket_types"."fest_id" INNER JOIN "role_types" ON "role_types"."id" = "tickets"."role_type_id" WHERE "tickets"."participant_id" = $1 AND (fests.id IN (COALESCE(1, 18, 19, 26))) AND (role_types.name LIKE 'volunteer%')

**Comment by petergoldstein** [comment]
I'm getting this error with 0.10.3 on a Redshift query

ERROR:skylight::c_api: failed to lex SQL query; err=LexError { kind: UnknownLexError, desc: "unknown sql lex error", pos: 2 }; sql=COPY dmarc_report_records
FROM 's3://bucketname/yyyyy/com.xxxxx/com.xxxx/2016/0310/1457664460.30626/manifest.json'
CREDENTIALS 'aws_access_key_id=XXXXXXXXX;aws_secret_access_key=XXXXXXXX'
MANIFEST
CSV

[SKYLIGHT] internal error: failed to lex SQL query

**Comment by abepetrillo** [comment]
Also getting this error on 1.0.0

**Comment by EvanMcEwen** [comment]
Just received this error on 1.0.0 today.
