### ISSUE TITLE
Default logger has no size limit

### ISSUE THREAD

**Issue by seanlinsley** [skylightio/skylight-ruby#55]
It looks like the default logger doesn't have a size limit. My current `skylight.log` file on production is 1.4 GB in size.

**Comment by wagenet** [comment]
@seanlinsley sorry about this. FWIW, I don't believe Rails limits log size either (though maybe this has changed). You can further customize the Skylight logger as documented here: https://docs.skylight.io/getting-set-up/#agent-configuration-rails-logger. You can then use one of the options on the Logger class to handle truncation: http://ruby-doc.org/stdlib-2.1.0/libdoc/logger/rdoc/Logger.html#method-c-new.

By the way, is there anything useful in the logs? If it's mostly useless noise, maybe we can clean it up a bit. If it's useful stuff we probably should talk about that too :) Shoot us an email at support@skylight.io to follow up.
