### ISSUE TITLE
failed to lex SQL query

### ISSUE THREAD

**Issue by rainerborene** [skylightio/skylight-ruby#57]
ERROR:skylight::c_api: failed to lex SQL query; err=LexError { kind: UnknownLexError, desc: "unknown sql lex error", pos: 15 }; sql=SELECT  "bills".id, "bills".title, "bills".slug, "bills".summary, "bills".image_file_name, "bills".politicians_count, "bills".status, "bills".cached_category_list, "bills".updated_at, "bills".last_mentioned_urls, "bills".publisher_ids, "bills".namespace_id FROM "bills" WHERE ("bills"."namespace_id" IS NOT NULL) AND (cached_tag_list && ARRAY['cigarro','espaco publico','fumar']) AND ("bills"."id" != $1) LIMIT 3

**Comment by wagenet** [comment]
Thanks for reporting this. The issue here is that our lexer doesn't yet handle arrays. The good news is that this error doesn't prevent your app from operating or reporting data to Skylight. It just means that we can't show as much detail about these specific queries.

**Comment by wagenet** [comment]
@rainerborene I've just rolled out an update in 1.0.0-beta3 that should handle arrays correctly. Let me know if you get to try it out.
