### ISSUE TITLE
error: enumerator value for ‘RUBY_FL_USER19’ is not an integer constant expression

### ISSUE THREAD

**Issue by jnimety** [skylightio/skylight-ruby#64]
I'm prepping for an upgrade from Fedora 22 to Fedora 24 and ran into this issue during initial bundle install.  We use puppet to manage our server deploys and all gems install successfully on Fedora 22.

```
current directory: /home/capistrano/.rvm/gems/ruby-2.3.1/gems/skylight-0.10.3/ext
/home/capistrano/.rvm/rubies/ruby-2.3.1/bin/ruby -r ./siteconf20160511-29465-im0kfx.rb extconf.rb
I, [2016-05-11T19:16:02.065993 #29487]  INFO -- : SKYLIGHT_HDR_PATH=/home/capistrano/.rvm/gems/ruby-2.3.1/gems/skylight-0.10.3/ext; SKYLIGHT_LIB_PATH=/home/capistrano/.rvm/gems/ruby-2.3.1/gems/skylight-0.10.3/lib/skylight/native/x86_64-linux
I, [2016-05-11T19:16:02.066314 #29487]  INFO -- : [SKYLIGHT] fetching native ext; curr-platform=x86_64-linux; requested-arch=x86_64-linux; version=0.7.0-b2a5f4b
I, [2016-05-11T19:16:02.066423 #29487]  INFO -- : [SKYLIGHT] attempting to fetch from remote; uri=https://s3.amazonaws.com/skylight-agent-packages/skylight-native/0.7.0-b2a5f4b/skylight_x86_64-linux.tar.gz
I, [2016-05-11T19:16:02.287940 #29487]  INFO -- : [SKYLIGHT] successfully downloaded native ext; out=/home/capistrano/.rvm/gems/ruby-2.3.1/gems/skylight-0.10.3/ext/skylight_x86_64-linux.tar.gz
skylightd
libskylight.so
skylight.h
skylight_dlopen.h
skylight_dlopen.c
checking for skylight_dlopen.h in /home/capistrano/.rvm/gems/ruby-2.3.1/gems/skylight-0.10.3/ext... yes
checking for dlfcn.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for fast thread local storage... yes
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/capistrano/.rvm/gems/ruby-2.3.1/extensions/x86_64-linux/2.3.0/skylight-0.10.3/mkmf.log

current directory: /home/capistrano/.rvm/gems/ruby-2.3.1/gems/skylight-0.10.3/ext
make "DESTDIR=" clean

current directory: /home/capistrano/.rvm/gems/ruby-2.3.1/gems/skylight-0.10.3/ext
make "DESTDIR="
compiling skylight_dlopen.c
compiling skylight_native.c
In file included from /home/capistrano/.rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/ruby.h:33:0,
                 from skylight_native.c:2:
/home/capistrano/.rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/ruby/ruby.h:841:45: error: enumerator value for ‘RUBY_FL_USER19’ is not an integer constant expression [-Werror=pedantic]
 #define RUBY_FL_USER_N(n) RUBY_FL_USER##n = (1<<(RUBY_FL_USHIFT+n))
                                             ^
/home/capistrano/.rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/ruby/ruby.h:862:5: note: in expansion of macro ‘RUBY_FL_USER_N’
     RUBY_FL_USER_N(19),
     ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:238: recipe for target 'skylight_native.o' failed
make: *** [skylight_native.o] Error 1

make failed, exit code 2
```

**Comment by jnimety** [comment]
the gcc version changed from `gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)` to `gcc (GCC) 6.0.0 20160406 (Red Hat 6.0.0-0.20)`

**Comment by wagenet** [comment]
This isn't a constant we use directly in Skylight. It would seem that this is a problem with `ruby.h` and gcc 6.

**Comment by jnimety** [comment]
ok, thanks.  For what it's worth this installs skylight successfully: `gem install skylight -- --with-cflags=\"-Wno-error=pedantic\"`

**Comment by jnimety** [comment]
it looks like the `-pedantic` cflag at https://github.com/skylightio/skylight-ruby/blob/master/ext/extconf.rb#L209 is the culprit since that has the side effect of raising errors if ruby.h is not strictly iso compliant (at least not according to gcc 6.0)

**Comment by chancancode** [comment]
Good catch! Thanks for tracking this down, we will remove that flag. (I'll probably file a bug with Ruby too)

**Comment by jnimety** [comment]
another short term workaround `bundle config build.skylight --with-cflags=\"-Wno-error=pedantic\"`

**Comment by nobu** [comment]
As we also need other non-strict-ANSI features, e.g., 128bit integer, `-Wpedantic` is disabled.

**Comment by chancancode** [comment]
@nobu in that case we will remove it from our extconf! 👍

**Comment by epitron** [comment]
Please do! It's still there: https://github.com/skylightio/skylight-ruby/blob/master/ext/extconf.rb#L209

**Comment by aaronthewhite** [comment]
This issue was affecting me also.

**Comment by nofxx** [comment]
Even with the workaround, still can't install on Archlinux (GCC 6.1.1)

With `--with-cflags=\"-Wno-error=pedantic\"`

    error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]

Because of `-Werror` flag on extconf.rb?
https://github.com/skylightio/skylight-ruby/blob/master/ext/extconf.rb#L189

**Comment by mrzor** [comment]
@nofxx For Archlinux (GCC 6.1.1 20160707) `gem install skylight -- --with-cflags=\"-Wno-error=pedantic -O\"` does work.

**Comment by nofxx** [comment]
@mrzor thank you, `-O` did the trick =D

**Comment by mrzor** [comment]
@wagenet [mkmf.log](https://gist.github.com/mrzor/9be07f6db339a0f866301774c88b71e6) from running `gem install skylight -- --with-cflags=\"-Wno-error=pedantic\"`

**Comment by nofxx** [comment]
```
make "DESTDIR="
compiling skylight_memprof.c
In file included from /usr/include/stdio.h:27:0,
                 from /usr/include/ruby-2.3.0/ruby/defines.h:26,
                 from /usr/include/ruby-2.3.0/ruby/ruby.h:36,
                 from /usr/include/ruby-2.3.0/ruby.h:33,
                 from skylight_memprof.c:1:
/usr/include/features.h:331:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^~~~~~~
In file included from /usr/include/ruby-2.3.0/ruby.h:33:0,
                 from skylight_memprof.c:1:
/usr/include/ruby-2.3.0/ruby/ruby.h:841:45: warning: enumerator value for ‘RUBY_FL_USER19’ is not an integer constant expression [-Wpedantic]
 #define RUBY_FL_USER_N(n) RUBY_FL_USER##n = (1<<(RUBY_FL_USHIFT+n))
                                             ^
/usr/include/ruby-2.3.0/ruby/ruby.h:862:5: note: in expansion of macro ‘RUBY_FL_USER_N’
     RUBY_FL_USER_N(19),
     ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:239: skylight_memprof.o] Error 1

make failed, exit code 2
```

**Comment by wagenet** [comment]
Just wanted to say that we haven't forgotten about this issue. I've put together a fix but since I'm not an expert in this area I want to sanity check with some of the other team members.

**Comment by wagenet** [comment]
I added the following to my `tests/index.html` after the `<script src="assets/test-loader.js"></script>` line.

```js
    <script>
      Testem.afterTests(function() {
        if (window.__coverage__) {
          Object.keys(require.entries).forEach(function(file) {
            // Only load non-test files from our app
            var parts = file.split('/');
            if (parts[0] === 'direwolf' && parts[1] !== 'tests') {
              try {
                require(file);
              } catch(e) {
                throw 'error requiring file for coverage: '+file;
              }
            }
          });
        }
      });
    </script>
```

(`direwolf` is the app's name.)

**Comment by wagenet** [comment]
I've pushed out a branch of master with potential fixes here: https://github.com/skylightio/skylight-ruby/tree/remove-build-flags. There's a slight chance that it might affect performance so we'd like to do some benchmarking before putting it in an official build.

**Comment by wagenet** [comment]
This should be fixed with version 0.10.6.

**Comment by tuvistavie** [comment]
0.10.6 worked for me on ArchLinux with gcc 6.1.1 without touching any flags, thanks!

**Comment by bwr** [comment]
Do you plan to release a 1.0.0.betaX with this fix soon?
