### ISSUE TITLE
License

### ISSUE THREAD

**Issue by reiz** [skylightio/skylight-ruby#68]
What is the name of your software license? Can we add the license information to the gemspec? 

I'm working on the open source [VersionEye](https://www.versioneye.com) and we provide license whitelists and license normalization to our clients. We have paying customers who are using the Skylight Gem, that's why we would like to add your license to our normalization algorithm. For that we need the official name of the license. Your help is highly appreciated.

**Comment by wagenet** [comment]
Sorry for this being so overdue. Our license is Nonstandard. I've updated the gemspec accordingly and it will be reflected in the next release.

**Comment by reiz** [comment]
Hi @wagenet. That's fine. That's all I want :-) 

If you create a custom license, which is not standard and doesn't existed before, then I would recommend to give it a proper name. For example the "Skylight-License".

**Comment by wagenet** [comment]
Rubygems only appears to allow for a specific set of names.

**Comment by wagenet** [comment]
Though I guess we could give it a title in the LICENSE.md
