### ISSUE TITLE
ERROR:skylight::c_api: failed to lex SQL query; err=LexError

### ISSUE THREAD

**Issue by bjeanes** [skylightio/skylight-ruby#69]
I'm getting a lot of these kinds of errors in my logs pretty regularly. I'm posting a few different queries that trigger it, though it isn't an exhaustive list:

```
SELECT count(*) FROM "table1" INNER JOIN "table2" ON "table2"."id" = "table1"."col1" INNER JOIN "table4" ON "table4"."col2" = "table1"."id" WHERE "table1"."col3" = 17619 AND (table1.col13 IS NULL) AND (table1.col9 = 'Value') AND (      (table1.col8 = 1 AND EXISTS (SELECT t3.id FROM table3 t3
        WHERE t3.col2 = table1.id
        AND t3.col4 IS NOT NULL
        AND t3.col5 IN (table1.col6, table1.col7)
        AND t3.col5 = 14329)
      )
      OR
      (table1.col8 = 2 AND EXISTS (SELECT col10 FROM table5
        WHERE table5.col4 IS NOT NULL
        AND table1.id = table5.col10
        AND table5.col5 IN (table1.col6, table1.col7)
        AND table5.col5 = 14329)
      )
) AND ((table1.col6 = '14329' AND table4.col11 OR table1.col7 = '14329' AND table4.col12))
```

```
SHOW max_identifier_length
```

```
SELECT count(*) FROM "table1"  WHERE "table1"."col2" = 17619 AND (table1.col3 IS NULL) AND (table1.col1 = 'Value') AND ('14329' not in (coalesce(table1.col4, 0), coalesce(table1.col5, 0))) AND (table1.col4 IS NULL OR table1.col5 IS NULL)
```

```
SELECT COUNT(*) FROM "table1"  WHERE "table1"."col13" = 17619 AND (table1.col6 IS NULL) AND (col5 = 'Value') AND (      (
  (table1.col10 = 1 AND (SELECT count(*) FROM table2 t2
   WHERE t2.col1 IN (table1.col2, table1.col3)
   AND t2.col9 = table1.id AND t2.col4 IS NOT NULL) = 2)
OR
  (table1.col10 = 2 AND (SELECT count(*) FROM table3 t3
  WHERE t3.col1 IN (table1.col2, table1.col3)
  AND t3.col12 = table1.id AND t3.col4 IS NOT NULL) = 2)
)
AND EXISTS (SELECT t4.id FROM table4 t4 WHERE t4.col7 = true AND t4.col8 = true AND t4.col9 = table1.id)
AND NOT (
  EXISTS (SELECT t4.id FROM table4 t4 WHERE t4.col11 = true AND t4.col9 = table1.id)
  AND (
    (table1.col10 = 1 AND EXISTS (SELECT t2.id FROM table2 t2 WHERE t2.col1 = 0 AND t2.col9 = table1.id AND t2.col4 IS NOT NULL))
    OR
    (table1.col10 = 2 AND EXISTS (SELECT t3.id FROM table3 t3 WHERE t3.col12 = table1.id AND t3.col1 IS NULL AND t3.col4 IS NOT NULL))
  )
)
```

Database is Postgres and Skylight gem version is 0.10.5

**Comment by wagenet** [comment]
Thanks for sharing these. User reports are the only way for us to know exactly what fails. We can't send these queries to our servers because theoretically they could contain sensitive data!

We've also got plans to make the logging less noisy as the current logging can sometimes be quite excessive if frequently called queries are unparseable.

**Comment by bjeanes** [comment]
@wagenet no worries. I'll post any others I come across. As you can see I did a rough manual pass at anonymising the table/column names but if they seem to have an effect on the parsing (I'd be surprised if so) I can re-provide without modification.

**Comment by h8rry** [comment]
Getting the same error with this SQL

```
(
  SELECT table1.*
  FROM table1
  INNER JOIN table2
    ON table2.something_id = table1.id
  INNER JOIN table3
    ON table3.id = table2.something_id
  WHERE table3.slug = 'something'
  ORDER BY table1.created_at DESC
)
```

Database is Postgres and Skylight gem version is 0.10.5

**Comment by wagenet** [comment]
This is long overdue, but the new SQL lexer supports these queries correctly. I expect to have a beta out in the coming weeks.

**Comment by Yanchek99** [comment]
Also running into this issue with Rails 5.2 (heroku/postgres) when active_storage queries are being initiated.

`ERROR:skylight::c_api: failed to lex SQL query; err=LexError { kind: UnknownLexError, desc: "unknown sql lex error", pos: 35 }; sql=SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_type" = $1 AND "active_storage_attachments"."name" = $2 AND "active_storage_attachments"."record_id" IN ($3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) `

**Comment by wagenet** [comment]
@Yanchek99 can you try the 2.0 agent beta?

**Comment by tehviking** [comment]
We're also getting a lot of lex errors on our queries like this... we'll try `2.0.0-beta3` and see if that helps.

**Comment by Yanchek99** [comment]
@wagenet I tried the 2.0 agent at it appears to have worked!  Not seeing anymore errors in my logs!

**Comment by tomca32** [comment]
We started getting these after performing an upgrade to `1.6.1` a couple of hours ago.
```
ERROR:skylight::c_api: failed to lex SQL query; err=LexError { kind: UnknownLexError, desc: "unknown sql lex error", pos: 15 }; sql=SELECT "groups".* FROM "groups" WHERE "groups"."chapter_id" IN ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
```

**Comment by wagenet** [comment]
@tomca32 I'd guess the 5.2 upgrade changed the queries as no changes to the SQL lexer have happened in the 1.x branch for a long time. However, upgrading to the 2.0 beta should resolve this issue.
