### ISSUE TITLE
Question about fanout implementation

### ISSUE THREAD

**Issue by lukeasrodgers** [skylightio/skylight-ruby#70]
I noticed a discrepancy between the query times reported by the rails logsubscriber (which uses the overwritten skylight fanout.rb/instrumenter.rb) and ASN subscriptions I had manually attached on our application; the more subscribers I attached, the greater the discrepancy seemed to be. 

Looking at the code, it seems that each subscriber for a given event will have slightly different start and end times: https://github.com/skylightio/skylight-ruby/blob/v0.6.0/lib/skylight/vendor/active_support/notifications/fanout.rb#L39-L45.

Differences will usually be small, but could be very large (well, by "very" I mean >1 ms in this context) if, e.g. GC runs between invocations. It seems to me that multiple subscribers for a given event should all see that event as the same, i.e. same start/end times.

I'm curious whether a) my understanding is correct, and b) this behaviour is intentional.

It looks like this is the approach taken by rails itself since https://github.com/rails/rails/commit/f08f8750a512f741acb004d0cebe210c5f949f28, but it seems flawed to me for the reasons mentioned.

thanks

**Comment by wagenet** [comment]
I'm pretty sure this code only gets applied in very old versions of Rails. I agree that this may be a potential issue, but the place to bring it up is probably with Rails Core itself. If there's an important fix, we can back port it for use in earlier versions.
