### ISSUE TITLE
File.expand_path raises ArgumentError if HOME env is not set

### ISSUE THREAD

**Issue by fotinakis** [skylightio/skylight-ruby#71]
A small odd bug for you: deep in some docker containers I had one that, probably misconfigured, did not have the `HOME` environment variable set. I probably wouldn't have noticed because everything else was working correctly, but the Skylight agent ended up dying hard on this line:

```ruby
File.expand_path(ENV["SKYLIGHT_USER_CONFIG_PATH"] || "~/.skylight")
```
https://github.com/skylightio/skylight-ruby/blob/5ef52c83797f272738d4cbba3aea6ee67c2e5380/lib/skylight/user_config.rb#L17

...because of this Ruby `File.expand_path` behavior when HOME is not set:

```ruby
> File.expand_path('~/.foo')
 => "/Users/user/.foo" 
> ENV.delete('HOME')
> File.expand_path('~/.foo')
ArgumentError: couldn't find HOME environment -- expanding `~'
  from (irb):3:in `expand_path'
  from (irb):3
  from /Users/user/.../irb:11:in `<main>'
 ```

Non-critical, just thought I'd report!

**Comment by wagenet** [comment]
@fotinakis Thanks for the heads up. What would you think is correct if `HOME` isn't sent?

**Comment by wagenet** [comment]
Closing in favor of #61.
