### ISSUE TITLE
Instrumenting multiple ActiveRecord database connections

### ISSUE THREAD

**Issue by bf4** [skylightio/skylight-ruby#72]
We have two databases that we connect to. Skylight instruments the 'main' one, from the database.yml, just fine. But, we have another, say 'datamart.yml', and we establish a connection to it in a class `class DatamartConnection < ActiveRecord::Base` that isn't being instrumented.

Can you help point me to how we can add this instrumentation? (and then see the SQL calls :)

**Comment by wagenet** [comment]
Got it, glad you figured it out :)
