### ISSUE TITLE
Skylight 1.0.0 causes failures when used in ActionController::Metal controllers

### ISSUE THREAD

**Issue by craigmcnamara** [skylightio/skylight-ruby#80]
I started pull request #79 to start a discussion about a solution to this issue.

**Comment by wagenet** [comment]
See 33491a8f7065206434d06c97cf031aa3c8485e9c. Will release 1.0.1 soon.

**Comment by sandstrom** [comment]
ping @wagenet 😄

**Comment by wagenet** [comment]
Sorry for the delay here. I've got some code ready to ship, just having to resolve a couple of issues around making a release. Aiming for today or tomorrow.

**Comment by wagenet** [comment]
Just released 1.0.1 with a fix for this issue.
