### ISSUE TITLE
Support for Sinatra::Namespace

### ISSUE THREAD

**Issue by dentarg** [skylightio/skylight-ruby#88]
It doesn't look like skylight-ruby understands the use of Sinatra::Namespace: http://www.sinatrarb.com/contrib/namespace.html

**Comment by wagenet** [comment]
Good idea. It shouldn't be too hard to make a PR for. I'll also add it to our own list.

**Comment by wagenet** [comment]
Judging by #99 this works. Let me know if you can figuring out a failing test case and I can reopen this.

**Comment by dentarg** [comment]
@wagenet does the Skylight UI understand namespaces now?

**Comment by wagenet** [comment]
@dentarg were you having issues with the UI? What is it displaying compared to what you expect?

**Comment by dentarg** [comment]
```ruby
namespace '/foo' do
  get '/hello' do
    ...
  end
end

namespace '/bar' do
  get '/hello' do
    ...
  end
end
```

was grouped together, under `/hello`

This was in January, and we have since moved on, so I don't know if that's the case anymore (hence my question).

**Comment by wagenet** [comment]
Judging by the tests here https://github.com/skylightio/skylight-ruby/pull/99 it should work. I'll probably need to set up a test app to confirm.

**Comment by wagenet** [comment]
Reopening until I've verified manually.
