### ISSUE TITLE
Skylight Platform Util does not always detect Alpine Linux/musl

### ISSUE THREAD

**Issue by ryansch** [skylightio/skylight-ruby#92]
`RbConfig::CONFIG['host_os']` seems to reflect the host OS in use when ruby was compiled.  If an alpine linux container is being built on an alpine host then we get `linux-musl` but if an alpine linux container is being built on a libc host then we get either `linux` or `linux-gnu`.

This means that the official `ruby:2.3.3-alpine` container will report `linux-gnu` back and install the wrong version of libskylight.  Here's a copy of my install.log from inside of a `ruby:2.3.3-alpine` container:

```
I, [2017-02-16T16:56:53.004002 #13693]  INFO -- : SKYLIGHT_HDR_PATH=/usr/local/bundle/gems/skylight-1.0.1/ext; SKYLIGHT_LIB_PATH=/usr/local/bundle/gems/skylight-1.0.1/lib/skylight/native/x86_64-linux
I, [2017-02-16T16:56:53.004332 #13693]  INFO -- : [SKYLIGHT] fetching native ext; curr-platform=x86_64-linux; requested-arch=x86_64-linux; version=1.0.1-fcb0e55
I, [2017-02-16T16:56:53.004660 #13693]  INFO -- : [SKYLIGHT] attempting to fetch from remote; uri=https://s3.amazonaws.com/skylight-agent-packages/skylight-native/1.0.1-fcb0e55/skylight_x86_64-linux.tar.gz
I, [2017-02-16T16:56:54.649761 #13693]  INFO -- : [SKYLIGHT] successfully downloaded native ext; out=/usr/local/bundle/gems/skylight-1.0.1/ext/skylight_x86_64-linux.tar.gz
```

This appears to be the root cause behind #59 and #91.

A more reliable way to detect alpine might be to inspect the contents of `/etc/os-release` or `/etc/alpine-release`.

**Comment by wagenet** [comment]
Huh, that's quite odd and seems like a bug in Ruby. However, unless we want to wait for a fix there I guess we'll have to work around it.

**Comment by wagenet** [comment]
@ryansch have you verified that it works if we use the musl version instead?

**Comment by ryansch** [comment]
@wagenet I'll fork and do that now.

**Comment by wagenet** [comment]
@ryansch thanks!

**Comment by wagenet** [comment]
FWIW, it seems very odd to me that they're building Ruby against libc when it will be used on a platform without it. I'm not sure how this isn't causing lots of problems elsewhere!

**Comment by ryansch** [comment]
@wagenet Ruby is being built against musl here but the value of `host_os` only seems to contain `musl` when alpine is the actual host os (not to be confused with container os).

**Comment by wagenet** [comment]
@ryansch hmm... I could have sworn I got this to work when Linux was the host! Definitely something weird going on, but Docker isn't my strong suit :/

**Comment by ryansch** [comment]
@wagenet I can confirm that rails does start now with the musl version of libskylight installed.

Hack: https://github.com/skylightio/skylight-ruby/compare/master...outstand:hardcode-musl

**Comment by wagenet** [comment]
@ryansch thanks for checking this! I'll try to get a proper fix in place soon.

**Comment by ryansch** [comment]
@wagenet Do you need a small container to test with?

**Comment by wagenet** [comment]
Looks like `RbConfig::CONFIG['arch']` should be safer. Verifying the value on other platforms.

**Comment by ryansch** [comment]
@wagenet Doesn't look reliable here.

<img width="361" alt="screen shot 2017-02-16 at 11 27 27 am" src="https://cloud.githubusercontent.com/assets/146013/23037383/fad9c6e8-f43a-11e6-9582-4e02d7480260.png">

**Comment by ryansch** [comment]
@wagenet Have a look at the output of `ldd --version`.

<img width="287" alt="screen shot 2017-02-16 at 11 31 33 am" src="https://cloud.githubusercontent.com/assets/146013/23037530/8eda7f18-f43b-11e6-8602-a30f0581b25d.png">

**Comment by wagenet** [comment]
Ah, I was building Ruby as part of the `RUN` in my Dockerfile. Looks like on the official Ruby Alpine images there is no mention of musl in all of `RbConfig` 😞 .

**Comment by ryansch** [comment]
Exactly. Comparing the Dockerfile vs the APKBUILD didn't show anything obvious.

**Comment by wagenet** [comment]
I'm thinking of doing this:

```
      OS = case os = RbConfig::CONFIG['host_os'].downcase
      when /linux/
        if ENV['SKYLIGHT_MUSL'] || `ldd --version 2>&1` =~ /musl/
          "linux-musl"
        else
          "linux"
        end
```

**Comment by wagenet** [comment]
I don't love it, but I'm not sure of a better way to handle this.

**Comment by ryansch** [comment]
@wagenet I think that's the best solution right now.

**Comment by wagenet** [comment]
Should be fixed in 138bb9ab67edfe2c5253ab78964fef3f11405030

**Comment by wagenet** [comment]
@ryansch thanks again for your help here!

**Comment by ryansch** [comment]
@wagenet And thanks for yours!
