### ISSUE TITLE
How do you configure a proxy?

### ISSUE THREAD

**Issue by edjames** [skylightio/skylight-ruby#93]
Hi,

How do I configure Skylight to work with a proxy?

In the source I see a few things that reference the use of a proxy but I'm not sure if all I need to do is set an environment variable, or if something else is required. I also see two different environment variable names.

I've seen this:

https://github.com/skylightio/skylight-ruby/blob/master/lib/skylight/config.rb#L42

...and this:

https://github.com/skylightio/skylight-ruby/blob/63c1c509bcb99569e4251b1ea608873bc1a060c3/lib/skylight/util/proxy.rb#L5

Any guidance would be appreciated.

Thanks,
Ed.

**Comment by wagenet** [comment]
@edjames we generally recommend setting `HTTP_PROXY` in your environment. It looks like you've also contacted us via our support channel so we can continue any discussion there. :)
