### ISSUE TITLE
Failed to lex SQL query (likely array related)

### ISSUE THREAD

**Issue by pnomolos** [skylightio/skylight-ruby#97]
I can't put the entire statement here, but I believe the section in question that's failing (based on previous tickets) is likely the following bit:

`"imported_files" = ARRAY['type','another','something','else']::character varying[]`

**Comment by wagenet** [comment]
@pnomolos that sounds plausible. I've been working on a new lexer that, with any luck, will help here. Unfortunately, I don't have an ETA. These errors will not affect overall operation of Skylight, though they may reduce what is visible in the UI.

**Comment by jesperronn** [comment]
Possibly related to #81

**Comment by wagenet** [comment]
@pnomolos this is way overdue, but can I ask what SQL variant you're using?

**Comment by wagenet** [comment]
I also think the new SQL lexer will resolve this. I expect a beta to be released in the coming weeks.

**Comment by pnomolos** [comment]
@wagenet We're on Postgres 9.6.
